### ISSUE TITLE
Генерировать id для заголовков

### ISSUE THREAD

**Issue by MeFoDy** [web-standards-ru/web-standards.ru#10]
11ty позволяет генерировать при помощи `markdown-it-anchor` якоря для заголовков: https://github.com/11ty/eleventy-base-blog/blob/master/.eleventy.js

Это может быть удобно для ссылки на конкретный участок статьи. Сам пользуюсь, если сайты такое предусматривают.

**Comment by pepelsbey** [comment]
Я уже решаю это на 11ty с помощью [такого кода](https://github.com/fword-dev/f-word.dev/blob/master/.eleventy.js#L75-L80), который расширяет встроенный `markdown-it` плагином `markdown-it-named-headings`. К нему нужно добавить якорь и что-то такое, да.

Вопрос только в том, как кириллические заголовки превращать в полезные якоря.

**Comment by vitalybaev** [comment]
Давайте возьму в работу. `markdown-it-anchor` вполне хорошо выполняет эту задачу.

>Вопрос только в том, как кириллические заголовки превращать в полезные якоря.

Посмотрел на GitHub - они ничего не делают особенного с кириллицей. Думаю мы можем пойти по тому же пути.

Единственный вопрос - как это должно выглядеть визуально по вашему мнению?
1. Какой символ использовать: `¶`, `#` или что-то еще?
2. Где размещать этот символ - до или после заголовка?
3. Держать его всегда видимым или же как на GitHub показывать его только по ховеру?

Это все вопросы, для того, чтобы выполнить задачу

**Comment by pepelsbey** [comment]
> Какой символ использовать: ¶, # или что-то еще?

Лучше #, он нашей гиковской публике знаком лучше

> Где размещать этот символ - до или после заголовка?
> Держать его всегда видимым или же как на GitHub

Я бы попробовал вставить сразу после текста и всегда видимым

**Comment by vitalybaev** [comment]
@pepelsbey Принял, тогда приступаю к работе, назначь, пожалуйста, ишью на меня :)

**Comment by pepelsbey** [comment]
> Посмотрел на GitHub - они ничего не делают особенного с кириллицей

Потому, что это американская компания. А наши ссылки в итоге будут выглядеть страшновато. Вот, например, какой будет ссыла на заголовок [из статьи Сары](https://web-standards.ru/articles/what-accessibility-taught-me/):

https://web-standards.ru/articles/what-accessibility-taught-me/#javascript-%D0%BD%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC-%D0%B4%D0%BB%D1%8F-%D0%BF%D0%BE-%D0%BD%D0%B0%D1%81%D1%82%D0%BE%D1%8F%D1%89%D0%B5%D0%BC%D1%83-%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%BD%D1%8B%D1%85-%D0%BA%D0%B0%D1%81%D1%82%D0%BE%D0%BC%D0%BD%D1%8B%D1%85-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D1%8B%D1%85-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2

Я бы лучше делал по-другому: можно считать заголовки и раздавать им id плагином. Например, вот этот заголовок 3-й в контенте статьи:

```
<h2 id="section-3">JavaScript необходим для по-настоящему доступных кастомных интерактивных компонентов</h2>
```

И ссылка будет https://web-standards.ru/articles/what-accessibility-taught-me/#section-3

**Comment by vitalybaev** [comment]
Точно, браузеры же декодируют сейчас такие вещи, поэтому на коротких заголовках проблемы особо и нет.

>Я бы лучше делал по-другому: можно считать заголовки и раздавать им id плагином

После беглого просмотра не увидел, что в `markdown-it-anchor` можно получить такую информацию.

Вариант с транслитерацией первое что приходит в голову, но для твоего решения нужно больше времени изучить вопрос :)
