### ISSUE TITLE
Скроллбар в блоке кода

### ISSUE THREAD

**Issue by zateya** [web-standards-ru/web-standards.ru#104]
Не очень удобная область для захвата, маленькая по высоте
![image](https://user-images.githubusercontent.com/22032467/84467032-8b8a2080-ac83-11ea-9f36-0a034a4066ab.png)

Может быть, или увеличить или сделать увеличение на ховер, как в vk

![image](https://user-images.githubusercontent.com/22032467/84467100-bffddc80-ac83-11ea-9264-1b92a43cb0cb.png)

Может быть субъективно, конечно...

**Comment by pepelsbey** [comment]
Очень «за»!

**Comment by KazakovAS** [comment]
Поддерживаю, особенно 2 вариант лаконичнее кажется

**Comment by pepelsbey** [comment]
@zateya а принесите нам реализацию пулреквестом? :) Будем очень благодарны

**Comment by zateya** [comment]
Мне немного страшно влезать своими лапами в ваш аккуратный код.
Давайте пока сделаю вроде демки, может у ребят появятся идеи реализации гораздо лучше.

Сделала пример (надеюсь, он откроется)
https://zateya.github.io/scrollbar/

Еще также заметила, что крайнее положение скрола не очень, закрывается псевдо-элементом, который мешает, но как лучше сделать - не знаю

![image](https://user-images.githubusercontent.com/22032467/89098342-53839c00-d3ef-11ea-9e1b-cd821b87acfc.png)

**Comment by Holiden** [comment]
Постараюсь сегодня вечером сделать ПР.

**Comment by pepelsbey** [comment]
Спасибо @Holiden, он всё сделал :)
