### ISSUE TITLE
Обрезание контента

### ISSUE THREAD

**Issue by umado** [web-standards-ru/web-standards.ru#108]
##  `code`

**Шаги воспроизведения:**
1. Открыть [Puppeteer для кра­у­лин­га стра­ниц сай­та и со­хра­не­ния их в Markdown](https://web-standards.ru/articles/puppeteer-crawl-to-markdown/)
2. Установить ширину вьюпорта 320px
3. Найти `Array.from(document.querySelectorAll(selector))`
4. Посмотреть на то, как он не влезает:

![1](https://user-images.githubusercontent.com/67333731/85433990-01e52780-b58e-11ea-8949-f0dc3a58a1fb.png)

## Таблицы

**Шаги воспроизведения:**
1. Открыть [Уско­ря­ем­ся с по­мо­щью Browserslist](https://web-standards.ru/articles/speed-up-with-browserslist/) 
2. Установить ширину вьюпорта 320px
3. Найти таблицы
4. Посмотреть на то, как они не влезают:

![2](https://user-images.githubusercontent.com/67333731/85434706-2097ee00-b58f-11ea-959a-4798bdfb8eef.png)

**Comment by pepelsbey** [comment]
Видимо, нужно `break-word` для `.content code` делать.

**Comment by akellbl4** [comment]
@pepelsbey починено можно закрыть :)

**Comment by pepelsbey** [comment]
Огонь!
