### ISSUE TITLE
Увеличить шрифт на мобильных разрешениях

### ISSUE THREAD

**Issue by baradusov** [web-standards-ru/web-standards.ru#11]
На смартфоне 12px заставляют напрягать глаза при чтении статьи. Хотелось бы как минимум 16px.

**Comment by dangreen** [comment]
Добавлю что есть плагин [stylelint-a11y](https://github.com/YozhikM/stylelint-a11y), и в нем есть правило [`font-size-is-readable`](https://github.com/YozhikM/stylelint-a11y/blob/master/src/rules/font-size-is-readable/README.md).

> Disallow font sizes less than 15px (or 11.25pt).
> ...
> - [Marvel](https://blog.marvelapp.com/body-text-small/)

**Comment by pepelsbey** [comment]
Есть два способа решить эту задачу:

1. Увеличить шрифт в текущей вёрстке (к сожалению, такой размер был в дизайне)
2. Подождать перевёрстки по новому дизайну (он пока не закончен)

**Comment by Holiden** [comment]
> Есть два способа решить эту задачу:
> 
> 
> 
> 1. Увеличить шрифт в текущей вёрстке (к сожалению, такой размер был в дизайне)
> 
> 2. Подождать перевёрстки по новому дизайну (он пока не закончен)

Мне кажется увеличить шрифт сейчас не составит труда. А в новом дизайне это обязательно учесть.
