### ISSUE TITLE
Логическая ошибка в статье «Ускоряемся с помощью Browserslist»

### ISSUE THREAD

**Issue by MikeDevice** [web-standards-ru/web-standards.ru#114]
В данной [статье](https://web-standards.ru/articles/speed-up-with-browserslist/) есть такой кусок текста:

> last 2 years
> 1%
not dead
>
> Этот пример файла .browserslistrc означает, что вам нужны живые браузеры за последние два года, у которых больше 1% пользователей.

Если проверить данный конфиг на сайте browserlist, то можно увидеть, что в выборку попадают браузеры, у которых меньше одного процента пользователей: [`last 2 years, >1%, not dead`](https://browserl.ist/?q=last+2+years%2C+%3E1%25%2C+not+dead). В документации сказано, что запятая равносильна `or`, но даже если явно указать `and`, то всё равно будут браузеры с количеством пользователей меньшим единицы, хотя их и станет сильно меньше: [`last 2 years and >1% and not dead`](https://browserl.ist/?q=last+2+years+and+%3E1%25+and+not+dead).

Очень интересно, конечно. Что думаете на этот счёт?

**Comment by pepelsbey** [comment]
@dangreen, что скажешь?

**Comment by dangreen** [comment]
Эту ошибку уже давно заметили, видимо пришло время все-таки её исправить 🙂.
