### ISSUE TITLE
Ссылка в README.md на конфиг Browserlist указывает не на те строки

### ISSUE THREAD

**Issue by MikeDevice** [web-standards-ru/web-standards.ru#115]
Вот ссылка, которая указана в README.md: https://github.com/web-standards-ru/web-standards.ru/blob/master/package.json#L40-L44.

Можно, конечно, указать новые (правильные строки), но рано или поздно ссылка всё равно станет указывать не туда, если `package.json` будет как-то меняться. Можно указать ссылку на конкретный коммит, но в таком случае, если будет меняться конфиг Browserlist, то ссылка в `README.md` уже будет ссылаться на устаревшую версию, что не очень хорошо, так что скорее всего, наверное, лучше просто эту ссылку убрать.

**Comment by pepelsbey** [comment]
Спасибо, поправил :)
