### ISSUE TITLE
Проставить размер для img

### ISSUE THREAD

**Issue by GoodwillDarina** [web-standards-ru/web-standards.ru#137]
Стоит добавить для картинок (и для видео наверное) хотя бы ширину, т.к. при загрузке сайта без стилей картинки имеют произвольный размер. Можно поставить по дефолту `width="100%"`, а в стилях потом перебить на `auto`.

**Comment by pepelsbey** [comment]
> при загрузке сайта без стилей картинки имеют произвольный размер

Мы не рассматриваем это как реальную ситуацию использования сайта. RSS, режим для чтения (когда тоже нет стилей) — это реальные сценарии, а этот всё же фантастический. Ну и атрибут `width` не принимает единицы измерения, включая проценты, любое число внутри считается пикселями.

Я пока закрою ишью, но если есть какие-то подробности: ссылки на статьи, скриншоты — добавляйте, можно будет открыть снова.
