### ISSUE TITLE
Сделать кеш-бастинг

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#14]
Чтобы после обновления вёрстки ничего не ехало из-за старых стилей или не ломалось из-за старых скриптов. Имена файлов будут включать их хеш-сумму.

[Решение что-то вроде этого](https://github.com/fword-dev/f-word.dev/blob/master/gulpfile.js#L57-L87): gulp-rev + gulp-rev-rewrite.

- Закешировать нужно только ресурсы из вёрстки, статьи трогать не нужно.
- Есть всякие неявные ресурсы, типа иконок, манифестов и прочего — нужно решить, что кешировать.

**Comment by alkorlos** [comment]
Увидел что есть ссылка на пример уже после того как все закончил, но в целом суть одна.
Я добавляю хеш к файлу стилей, файлу скриптов и svg спрайту. Не уверен что имеет смысл добавить его к отдельным иконкам, но это можно легко сделать с текущим шаблоном кода.
