### ISSUE TITLE
Поддержать несколько авторов

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#143]
Прямо сейчас код почти не готов, только местами:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/105274/97030679-c7a18c00-1567-11eb-8776-085f1ec182fe.png">

<img width="228" alt="image" src="https://user-images.githubusercontent.com/105274/97030703-d5571180-1567-11eb-8c31-80e115309a0b.png">

Путь к картинке: `/people/vadim-makeev,nikita-dubko/photo.jpg` и так далее.

Для этого конечно нужен ещё и дизайн.

**Comment by higimo** [comment]
@pepelsbey а сможешь тут дизайн нарисовать?=)

Я не очень понял, выглядит, словно ты хочешь объединить две картинки. Это, насколько я понимаю, тоже не сделано. Может, показывать две (и более) картинки?
![image](https://user-images.githubusercontent.com/2804205/104863448-ee911380-5946-11eb-8f3c-aef0fcd33109.png)

**Comment by vasiliy-dudin** [comment]
Есть 4 возможных решения по дизайну. Вадим, что думаешь? Какой выберем?

### 1. `<img>` уменьшаем и накладываем друг на друга.
 Хорош тем, что не раздувает список статей. 
Положение капель на скриншоте примерное. 
![image](https://user-images.githubusercontent.com/3635323/148087097-8edd87f0-c305-4eed-8ff8-dd13da8cab27.png) ![image](https://user-images.githubusercontent.com/3635323/148087140-c620f73d-093a-419d-925f-1c5d4705bb6d.png)

### 2. Размещаем все `<img>` в одной капле.
Наверное, можно как-то через object-fit их распределить автоматически. Но сначала надо убедиться, что лица авторов будут нормально обрезаться. 
![image](https://user-images.githubusercontent.com/3635323/148087407-0e290705-f161-44df-afd5-fbb5485936b9.png)

### 3. Будет выглядеть как предыдущий вариант, но img будет один. Готовить такую каплю каждый раз вручную в Фигме.
Возможно, самый дешёвый и беспроблемный способ. Но сменить аватар автору для всех его статей будет чуть сложнее.

### 4. Отображать новые `<img>` рядом.
Дешёво, но раздувает списки.
Или можно выбрать такое отображение только на странице статьи. А в других местах использовать другой вариант.
![image](https://user-images.githubusercontent.com/3635323/148087451-65cec313-c176-4587-8adb-a8aab6b704d8.png) 
![image](https://user-images.githubusercontent.com/3635323/148088298-3b674a8e-6e19-424f-af00-c1850c44fc2f.png)

**Comment by vasiliy-dudin** [comment]
И какое максимальное количество соавторов будем поддерживать?

**Comment by pepelsbey** [comment]
Я бы что-нибудь такое сделал лучше

![image](https://user-images.githubusercontent.com/105274/148274279-854086bc-444e-43da-856a-9d62307e6f3e.png)

В таком случае можно не ограничивать количество, но мы будем стараться избегать таких случаев в принципе. Со скрипом — двое. Если никак вообще — трое. Но не больше.

**Comment by vasiliy-dudin** [comment]
Ага, тоже хорошо, давай так. На всякий случай это ещё в Фигме нарисую для всех состояний

**Comment by vasiliy-dudin** [comment]
Таня наверстала несколько авторов без революционных изменений макета. 
Посмотри, плз, всё ли хорошо по расположению, отступам и переносам имён?


### Главная: десктоп, все типы карточек
![Главная,_десктоп,_все_типы_карточек](https://user-images.githubusercontent.com/3635323/149678542-4c83bfcb-cd56-4028-9a90-c1a68b0520cd.png)

### Главная: мобильник 1
![Главная, мобильник 1](https://user-images.githubusercontent.com/3635323/149678585-490319a8-eb02-4394-b571-066aec585682.png)

### Главная: мобильник 2
![Главная, мобильник 2](https://user-images.githubusercontent.com/3635323/149678588-1eb25a70-8115-47bc-b6ba-902b7543357b.png)

### Главная: планшетник
![Главная, планшетник](https://user-images.githubusercontent.com/3635323/149678598-547d9ef0-d0f4-4762-8a7f-0232bec46936.png)

### Все статьи, планшетник
![Все статьи, планшетник](https://user-images.githubusercontent.com/3635323/149678508-981022b5-bef3-41fd-a4b4-ba661cf7b9ed.png)

**Comment by pepelsbey** [comment]
@vasiliy-dudin выглядит огненно :)

**Comment by pepelsbey** [comment]
Готово!
