### ISSUE TITLE
Перевести статью Effective Collaboration with Product and Design

### ISSUE THREAD

**Issue by firefoxic** [web-standards-ru/web-standards.ru#153]
Статья про важность общения с дизайнерами и ПМ, и про то, как это общение выстроить.
Мне кажется статья очень важной, так как очень редко можно встретить хорошую коммуникацию разработчиков с дизайнерами, и это выливается в кучу проблем и негатива, а в итоге в некачественный продукт в руках пользователей.

**Comment by TimurSyrlybayev** [comment]
Я готов перевести статью. Вадим, подскажите, пожалуйста, как мне потом законтрибьютить перевод в данный пулл-реквест?

**Comment by pepelsbey** [comment]
@TimurSyrlybayev предлагаю такой воркфлоу:

1. Вы берёте часть текста и переводите: от заголовка к заголовку, например
2. Идёте в пулреквест с оригинальным текстом, выделяете эти строки и добавляете комментарий
3. В комментарии вы добавляете «предложение» (suggestion) и пишете туда перевод

Выглядит это так:

<img width="795" alt="Screenshot 2020-11-18 at 13 18 14" src="https://user-images.githubusercontent.com/105274/99517750-c74ab400-29a0-11eb-8579-e7c2362c456f.png">

4. Потом жмёте «Add single comment» и этот кусочек принимает редактор.

**Comment by TimurSyrlybayev** [comment]
@pepelsbey 
Понял, так и сделаю. Спасибо за разъяснения!

**Comment by pepelsbey** [comment]
@TimurSyrlybayev киньте ещё сюда данные [по примеру](https://github.com/web-standards-ru/web-standards.ru/tree/master/src/people/vadim-makeev), мы добавим карточку переводчика.

**Comment by TimurSyrlybayev** [comment]
@pepelsbey
В виде файла формата md или достаточно здесь написать? Если файлом оформлять не нужно, то вот:

Тимур Сырлыбаев, https://github.com/TimurSyrlybayev

Фотография тоже нужна?

**Comment by pepelsbey** [comment]
@TimurSyrlybayev за вас уже [всё сделали](https://github.com/web-standards-ru/web-standards.ru/pull/154/commits/9a61a50d584b14ef4a8d892944d371a8c6b7add9) :)

**Comment by TimurSyrlybayev** [comment]
@pepelsbey
А ну, всё супер тогда)
