### ISSUE TITLE
Ссылка на patreon в меню хедера показывается под футером в safari ios  при скролле

### ISSUE THREAD

**Issue by m0rg0t** [web-standards-ru/web-standards.ru#163]
Ссылка на patreon в меню хедера (разворачиваемого по нажатию на иконку "бургеры") в обычном режиме также показывается под футером в safari ios (14.2) во время скролла страницы.

Скриншоты такого поведения:

![image](https://user-images.githubusercontent.com/634236/103955060-8c6e2c80-5156-11eb-8fc9-ee07ec32d0a9.png)

![image](https://user-images.githubusercontent.com/634236/103955090-9a23b200-5156-11eb-978e-04b157914110.png)

Пример той же ссылки на патреон при открытом меню:
![image](https://user-images.githubusercontent.com/634236/103955182-cd664100-5156-11eb-9af4-b21ede457c5e.png)

**Comment by pepelsbey** [comment]
Спасибо! Знаем :) Сейчас [в работе](https://github.com/web-standards-ru/web-standards.ru/pull/159) новая шапка, которая эту проблему решает.
