### ISSUE TITLE
Единый макет?

### ISSUE THREAD

**Issue by firefoxic** [web-standards-ru/web-standards.ru#166]
Я в дизайне до сих пор разобраться толком не могу:
- Почему у нас два макета?
- Какой из них приоритетный?
- Если другой не приоритетный, то на что в нём надо смотреть, а на что не надо?
- Почему бы не собрать весь дизайн в один проект фигмы и не дополнить его всем, чего в нём не хватает?
- Видимо работа Игоря Штанга давно завершена, а кто сейчас дизайн допиливает и допиливает ли?
- Кроме тех ишью, в которых речь про разработку но упоминается, что под фичу надо и макет допилить, есть ли ещё какие-то цели/планы/etc по макету?

**Comment by pepelsbey** [comment]
Единого макета пока нет — для этого нужно дорисовать новый.

> Почему бы не собрать весь дизайн в один проект

Пока этим не занимались, но надо бы. Сначала найти бы дизайнера.

@higimo если есть планы по этому — расскажи :)

**Comment by higimo** [comment]
@pepelsbey пока вовсе нет плана, извините=( а ты рулишь обеими макетами? Давай с тобой посидим пол часика на созвоне, и подпишем что к чему там? Если ты не против. Уж хотя бы в одном можно указать что такой-то элемент см. там-то, но и там не доработан, см. такую-то задачу=)

**Comment by pepelsbey** [comment]
Давай!

**Comment by firefoxic** [comment]
А возможен какой-то вариант предлагать что-то по макету?
Пока вижу только копирование оригинала, правка его и шаринг ссылки на исправленное 🤔

**Comment by higimo** [comment]
@firefoxic 
> какой-то вариант предлагать что-то по макету?

Полагаю, вы можете заводить отдельные ишу на каждое предложение, а после апрува «артдиром» (пока что Вадим), поставим лейбл «дизайнеру», чтоб ишу была им выполнена.

**Comment by higimo** [comment]
@pepelsbey как договаривались, из этого ишу сгенерил задачи:

- Сгенерировать единый макет #187
- Дать ссылку в ридми на самый актуальный макет #188
- Актуализировать макет из ридми с самыми свежими решениями #189

Полагаю, теперь это можно закрыть, ведь вопрос исчерпан.

@firefoxic Вадим воспользуется своим админресурсом, чтобы привлечь дизайнеров. Задачи мы им сгенерили, работа есть. В целом, остаётся только ждать. Особенных работ по этой задаче не предвидится, маленькие шажки (которые могут делать даже разные дизы) уже есть в новых ишу.
