### ISSUE TITLE
Добавить h1 для главной страницы

### ISSUE THREAD

**Issue by alkorlos** [web-standards-ru/web-standards.ru#17]
Небольшая, но важная, задача из старого репозитория. На главную страницу нужно добавить h1 под visually-hidden.
Вроде бы в старой задаче речь шла еще о каких то проблемах с заголовками, кто нибудь помнит о каких?

**Comment by PsarewIvan** [comment]
Карточки статей начинаются сразу с h3.  Вопрос был в том: переписывать все заголовки карточек и последующие на h3 или задать h2 всему блоку со статьями

**Comment by pepelsbey** [comment]
Я бы сделал что-то вроде:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/105274/80583682-35398900-8a19-11ea-88ad-74f8f0fe0ebe.png">

Не очень элегантно, но как быстрый фикс — нормально.
