### ISSUE TITLE
Смайнить данные прошедших конференций

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/web-standards.ru#175]
- [x] найти откуда брать данные про прошедшие конференции
- [x] найти откуда брать видео с прошедших конференций
- [ ] смайнить данные в каком-нибудь json или yaml формате. Продуманность структуры данных менее важна, чем полнота данных. Майнить второй раз сложнее, чем удалять ненужное из готового файла.

----
Вероятно, для формирования первоначальной структуры данных помогут [ишу про галерею](https://github.com/web-standards-ru/web-standards.ru/issues/173) и [страницу конференции](https://github.com/web-standards-ru/web-standards.ru/issues/174). К тому же, можно смотреть на ишу про [формулирование структуры данных](https://github.com/web-standards-ru/web-standards.ru/issues/176).

**Comment by higimo** [comment]
@pepelsbey у тебя, наверно, есть какие-то ссылки на ресурсы? Можешь закинуть сюда, я бы сменил описание

**Comment by pepelsbey** [comment]
- Сайт https://wsd.events/
- Репозиторий https://github.com/web-standards-ru/wsd.events
- Видео https://www.youtube.com/c/Web-standardsRu/playlists

**Comment by DimonNikolaev** [comment]
Берусь за работу

**Comment by Semigradsky** [comment]
Можете тут взять, если будет удобнее: https://github.com/Semigradsky/events/tree/master/events/WSD
Брал информацию с сайта wsd.events
