### ISSUE TITLE
Добавить сортировку свойств в CSS и линтер к ней

### ISSUE THREAD

**Issue by alkorlos** [web-standards-ru/web-standards.ru#18]
Консистентность итогового кода важная вещь, если говорить про стили сейчас на проекте есть stylelint, но нет инструмента для проверки порядка и автоматической сортировки свойств. Сейчас, в большинстве файлов стилей, порядок: positioning, boxmodel, typography и т.д. соблюдается, но есть исключения и удобнее когда подобную работу делает машина.
Потенциальный кандидат для реализации этой задачи stylelint-order, файл с примером как это может выглядеть будет в pull request.
Основан этот файл на проекте https://github.com/constverum/stylelint-config-rational-order
Но этот проект давно не развивается, автор даже пул реквесты не принимает, новые свойства не добавляются. В любом случае, я думаю, удобнее иметь такой файл в проекте отдельно.

Обсудить можно вот что:

1. Альтернативные stylelint-order инструменты.
2. Предложенный порядок свойств. В значительной степени он соответствует тому что сейчас в проекте, и тем не менее.
3. Возможность разбить блоки правил пустыми строками.
4. Как лучше хранить эти правила отдельно или в package.json?
Меня устраивает предложенный порядок свойств.
Возможность разбить блоки правил пустыми строками я считаю удобной, но так как в проекте такого до сих пор не было, видимо, большинство разработчиков такое не использует.
Думаю когда файлы становятся слишком большими работать с ними становится сложнее так что я правила stylelint-order хранил бы отдельно и правила stylelint вынес из package.json.

Пишите что думаете, что нравится из этого что нет.

**Comment by alkorlos** [comment]
Дублирует задачу из старого репозитория, там началось обсуждение, но особо ни к чему не пришли кроме того что скорее всего будем использовать stylelint-order без разбиения блоков пустыми строками.

**Comment by neeptoon** [comment]
По моему скромному мнению разбиение блоков правил пустыми строками добавляет наглядности и в целом становится проще ориентироваться в коде.

**Comment by in-in** [comment]
Посмотрел PR для этой ишью — всё круто👍 на мой взгляд

Одно дополнение
На ряду с привычными `margin-top`, `margin-bottom`... нужно добавить `margin-block-end`, `margin-block-start`...(Logical Properties). Хоть сейчас это и черновик, но поддержка хорошая(87.8%). В любом случае за этим подходом будущее🤞

Ссылки по теме:

- https://caniuse.com/#feat=css-logical-props
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties
- https://github.com/csstools/postcss-logical

**Comment by pepelsbey** [comment]
> Хоть сейчас это и черновик, но поддержка хорошая(87.8%).
> В любом случае за этим подходом будущее

@in-in их наверное стоит добавить, но кажется вы переоцениваете их значимость. Они пришли не заменить margin-top и margin-bottom, они пришли стать альтернативой для лучшей адаптивности. То есть появление ремов не отменяет пиксели, а гриды не отменяют флексы.

**Comment by in-in** [comment]
_для истории_
про «заменить» я ничего не говорил - это чьи-то фантазии 😉

**Comment by pepelsbey** [comment]
> В любом случае за этим подходом будущее🤞

Я скорее об этом.

**Comment by alkorlos** [comment]
Добавил все логические свойства и еще кое что.
