### ISSUE TITLE
Сгенерировать единый макет

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/web-standards.ru#187]
Сейчас два макета (TODO: поставить ссылки)

**Comment by higimo** [comment]
@pepelsbey дай, пожалуйста, ссылки на макеты, я не очень понимаю о чём говорили в https://github.com/web-standards-ru/web-standards.ru/issues/166 какой из них «главный»?

**Comment by pepelsbey** [comment]
Главный макет один — https://www.figma.com/file/dV7oWbRYHt8W1076LueOOy
Но там не отрисован контент, то есть содержимое статьи. Именно поэтому у нас до сих пор есть старый макет, от которого мы уже давно ушли, на самом деле.

**Comment by pepelsbey** [comment]
Мне кажется, что задача некорректно сформулирована: нам не нужно генерировать единый макет, нам нужно в новом продолжить рисовать сайт. Старый можно использовать как референс местами, но про него лучше забыть.
