### ISSUE TITLE
Актуализировать макет из ридми с самыми свежими решениями

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/web-standards.ru#189]
- [ ] написать список свежайших решений

**Comment by higimo** [comment]
@pepelsbey есть ли что-то в старом макете, что нужно перенести в новый?

**Comment by higimo** [comment]
@pepelsbey как дела с привлечением дизайнеров и переносом дизайна? Может, что-то блокирует?

**Comment by pepelsbey** [comment]
@higimo дела хорошо: нашёл, объяснил задачу, начали работать.
