### ISSUE TITLE
Карточки статей не помещаются в 320px

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#191]
![image](https://user-images.githubusercontent.com/105274/105903852-75be4580-6031-11eb-8e26-0b8a2d4a0fce.png)

Возможно, нужно выпрямлять две колонки на узких экранах в одну.

**Comment by PsarewIvan** [comment]
Я это заметил когда делал #159 . Сейчас там размеры шрифтов не по макету, если их поправить - все начинает помещаться.
Но мне кажется все-таки лучше имя автора переносить на строчку ниже и делать шире

**Comment by pepelsbey** [comment]
> Но мне кажется все-таки лучше имя автора переносить на строчку ниже и делать шире

+1

**Comment by kmisha** [comment]
Привет!

Я думаю смогу это поправить.

**Comment by monochromer** [comment]
> Но мне кажется все-таки лучше имя автора переносить на строчку ниже и делать шире

Заголовки могут содержать длинные слова, которые выглядят не очень. Вариант - растягивать заголовок на две колонки:
![image](https://user-images.githubusercontent.com/6412192/112432472-c8cb2500-8d62-11eb-89ba-baba8c69a530.png)

**Comment by kmisha** [comment]
Привет!
Я думаю можно закрыть это issue, т.к, оно исправленно в #202
