### ISSUE TITLE
Выпилить «скопировать ссылку» из RSS

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#196]
(или выводить только для статьи в HTML)

![image](https://user-images.githubusercontent.com/105274/106311805-c2469280-6276-11eb-86f0-547c719eece9.png)

**Comment by pepelsbey** [comment]
@akellbl4 можешь посмотреть? 😁 Всё не можем закончить с этой фичей.

**Comment by akellbl4** [comment]
Ну ничего страшного, не ожидал что это ещё где-то вылезет :) сегодня гляну
