### ISSUE TITLE
Меню склеилось в Safari

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#199]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/105274/107159224-b3ab5a00-699f-11eb-8fe9-29502720d478.png">

Safari пока не поддерживает `column-gap: 8px` для флексов.

**Comment by pepelsbey** [comment]
@PsarewIvan тут немного кроссбраузерность хромает, поможете починить шапку? Нужно либо сделать грид, либо расставить отступ иначе.

**Comment by PsarewIvan** [comment]
@pepelsbey да, не доглядел. Завтра поправлю
