### ISSUE TITLE
Не работают ссылки в шапке

### ISSUE THREAD

**Issue by nlopin** [web-standards-ru/web-standards.ru#200]
1. Перейти на https://web-standards.ru/articles/
2. Кликнуть на любую ссылку в заголовке справа

Ожидаемое поведение: переход на другую страницу

Наблюдаемое: ничего не происходит

В тегах нет `href` аттрибута:
![image](https://user-images.githubusercontent.com/1469636/107244781-b2753e00-6a2e-11eb-9a76-b51d2b1de8b5.png)

**Comment by pepelsbey** [comment]
Это не ссылки, это будущие разделы и страницы сайта, которых пока нет :)
