### ISSUE TITLE
Починить фид статей

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#214]
Репортят:

> Привет, хотел добавить ваш сайт в рсс читалку, но там немного формат неверный, нужно искать способы обхода или вы можете поправить? Ключевая проблема в href у линка

Валидатор фидов W3C совсем не рад, [есть много претензий](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fweb-standards.ru%2Farticles%2Ffeed%2F).

Если возьмётесь — напишите!

**Comment by immitsu** [comment]
Я хочу!

Почти все ошибки из-за атрибута `href` у `link`. Надо привести к `<link>{{ url }}</link>`.
Плюс поправить формат у `guid` и `atom:link`.

**Comment by pepelsbey** [comment]
@immitsu тогда в бой :)

**Comment by pepelsbey** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/105274/112772852-d53dcf00-903b-11eb-8e3a-0cb6f8b48756.png">
