### ISSUE TITLE
<code> внутри <a> содержит лишние отступы

### ISSUE THREAD

**Issue by MeFoDy** [web-standards-ru/web-standards.ru#222]
В некоторых статьях, где есть `<code>` внутри `<a>`, используется костыль в виде отсутствующего пробела. Например, тут: [клац](https://web-standards.ru/articles/flutter-web-support/#section-5:~:text=%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D0%B2%D0%B0%D1%8E%D1%82%20%D1%82%D0%B5%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8EScrollbarTheme%D0%B8%20%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C).

При копировании такой текст даёт "поддерживают темизациюScrollbarThemeи возможность", что не очень красиво. Предлагаю чинить такое не кривым текстом, а стилями CSS.

**Comment by pepelsbey** [comment]
> Например, тут: клац.

Не у всех браузер на основе Chromium ;)

Это нужно чинить на уровне генератора или минификатора HTML, как мне кажется:

```html
темизацию<a href="…"><code>ScrollbarTheme</code></a>и возможность
```

Сам исходник такой.

**Comment by monochromer** [comment]
Просветите, в чём проблема? Я убрал пробелы - всё хорошо собралось и отобразилось.

**Comment by pepelsbey** [comment]
Я всё понял!

Это не «костыль в виде отсутствующего пробела», это видимо баг в типографе и он убирает пробелы между словами и маркдаун-ссылками. Я поправил это [в текущей статье](https://web-standards.ru/articles/flutter-web-support/) (и задеплоил) и посмотрю, нет ли таких же проблем в других.

Так что можно закрывать :) @MeFoDy проверь, плиз.

**Comment by pepelsbey** [comment]
Других таких проблем не нашёл `\S\[`

**Comment by MeFoDy** [comment]
Тоже больше нигде не нашёл. Но хочется придумать, как такое полечить и не проверять больше.

Подтюнить бы типограф.

**Comment by pepelsbey** [comment]
Завёл задачу [подтюнить типограф](https://github.com/web-standards-ru/web-standards.ru/issues/224).
