### ISSUE TITLE
Типограф склеивает слова со ссылками, если внутри код

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#224]
# Как воспроизвести

1. Запустить `npm run typograph -- src/articles/flutter-web-support/index.md -o`
2. Посмотреть `git diff`

# Ожидаемое поведение

Ничего (текст оттипографлен)

# Реальное поведение

Удаляются пробелы между словом и началом ссылки `[`

```diff
- размеры абзаца (класс [`paragraph`](https://api.flutter.dev/flutter/dart-ui/Paragraph-class.html))
+ размеры абзаца (класс[`paragraph`](https://api.flutter.dev/flutter/dart-ui/Paragraph-class.html))
```

---

Простой тест:

```md
Привет, [как]() дела.
Привет, [`как`]() дела.
```

Становится

```md
Привет, [как]() дела.
Привет,[`как`]()дела.
```

**Comment by pepelsbey** [comment]
@Mavrin привет, сможешь помочь немного? :)

**Comment by Mavrin** [comment]
Исправлено в версии 2.2.0

**Comment by pepelsbey** [comment]
@Mavrin спасибо!
