### ISSUE TITLE
Сделать пункт меню «Статьи» более явным

### ISSUE THREAD

**Issue by Seokky** [web-standards-ru/web-standards.ru#24]
![](https://downloader.disk.yandex.ru/preview/44cb83ec1fa6512d81cb2bbc206df44d12ff5f398c19725d3be6630a00fbda76/5ea95eca/3b-0TwUKxsBc_ewIzHoQqvTTO0bRd3e4DEAVWQ4w0vQKpwNKCrPc3Cn-FMSRPJaDxGRUvfGLJ8O9IkvS8uL9QQ==?uid=0&filename=2020-04-29_11-59-11.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=344186371&size=2048x2048)

При первом посещении сайта это меню казалось таким родным и интуитивно понятным: вот тебе ссылочки на странички, вот текущая выделена, остальные немного затемнены... Подождите-ка! Выделение ссылки "Статьи", оказывается, никак не связано с "current" элементом навигации. Это просто единственная реализованная страница, а серые - это те, которые будут реализованы позже. Так нас всё это время обманывали? Приевшийся за много лет шаблон пользовательского опыта, когда в навигационном меню выделена на фоне других ссылка на текущую страницу, разбит! Унижен, обруган и прогнан. 

А теперь нормальным языком и кратко. Вот ответ на вопрос из заголовка ишью: потому что глядя на это меню, юзер, который не первый день в вебе, не рассматривает других вариантов кроме того, что "Статьи" - это текущая страница, а серенькие - остальные. И когда он, насытившись контентом текущей страницы хочет перейти на следующую, тут то его и встречает `cursor: text` вместо предполагающегося `cursor: pointer`. Ну, вы поняли :)

**Comment by Holiden** [comment]
Неплохо :) Т.е. вы предлагаете убрать "выключенные" пункты меню?

**Comment by Seokky** [comment]
> Неплохо :) Т.е. вы предлагаете убрать "выключенные" пункты меню?

Эх, я забыл основное условие критики - предлагать. Если честно, не знаю, как здесь лучше поступить. Думаю, дизайном всё же можно как-то выразить "временную недосягаемость" этих ссылок, но вот как именно, сходу сказать не получается. Минимальное, что можно сделать без привлечения дизайнера, дружащего с UX, это добавить title при наведении. ![](https://downloader.disk.yandex.ru/preview/9c56770c2d5310ed2b7790511b3e1063ee3441c0f452e1fd3cae593ce99cbabd/5ea96c90/RqnWfRDUOOLMepbeGD7UUAmvBwjfaT2C_4hBYtp5qqaE4QXikVG4ove8l6Lijr8wVDk2-dm-Cs12mvdizbkRQA==?uid=0&filename=2020-04-29_12-58-40.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=344186371&size=2048x2048)

**Comment by Seokky** [comment]
Но это всё равно, к сожалению, не решит проблему визуального восприятия. Юзер всё так же будет видеть в элементе "Статьи" просто название текущей страницы - у него не возникнет мысль о том, что это ссылка на еще не посещенную им страницу.

**Comment by pepelsbey** [comment]
Предлагаю сделать так, как уже нарисовано в новой версии дизайна:

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/105274/80583154-872ddf00-8a18-11ea-812f-1c725c529872.png">

Подчеркнуть ссылку и сделать её синей.

**Comment by pepelsbey** [comment]
Сделал название чуть более прямолинейным.

**Comment by Seokky** [comment]
> Предлагаю сделать так, как уже нарисовано в новой версии дизайна:
> 
> <img alt="image" width="1105" src="https://user-images.githubusercontent.com/105274/80583154-872ddf00-8a18-11ea-812f-1c725c529872.png">
> 
> Подчеркнуть ссылку и сделать её синей.

Хм, а решает ли это описанную проблему?

> Но это всё равно, к сожалению, не решит проблему визуального восприятия. Юзер всё так же будет видеть в элементе "Статьи" просто название текущей страницы - у него не возникнет мысль о том, что это ссылка на еще не посещенную им страницу.

Сейчас мне пришла идея, как можно было бы избавиться от неоднозначности меню из-за наличия в нем недействительных "якобы-ссылок". Достаточно просто перед пунктом "Статьи" добавить пункт "Главная". Ну и приправить его стилями, которыми должен обладать текущий элемент меню согласно стайлгайду проекта. Тогда пользователь будет видеть, что сейчас он находится на главной, а можно еще перейти и в "Статьи". 

Затык в том, что как бы не стилизовался элемент "Статьи", в итоге это всё равно выглядит так, будто "Статьи" - текущая страница, а три серых ссылки ведут на еще не посещенные. Пользователь привык видеть два состояния элемента меню - "страница, на которую можно перейти" и "текущая страница". А недействительные ссылки на будущие страницы добавляют третье состояние "страница еще не реализована". 

Добавление пункта "Главная" позволит достичь ситуации, когда каждое из имеющихся состояний видно в любой момент времени. Тогда пользователь не будет принимать упомянутое выше состояние "страница, на которую можно перейти" за состояние "текущая страница" и с радостью посетит "Статьи", поскольку не будет думать, что он сейчас именно в них. 

P.S.: Надеюсь, никого не запутал :)

**Comment by pepelsbey** [comment]
Думаю, что контраст между синей подчёркнутой ссылкой и серым текстом достаточно громко говорит о том, что это не ссылки, а будущие разделы. В самом плохом случае, пользователь научится, когда кликнет.

Это слишком сложная проблема, на которую не хочется пока тратить слишком много времени. Я бы лучше сделал раздел «О проекте», который добавит вторую ссылку и уменьшит неоднозначность.

**Comment by Seokky** [comment]
Тут да, не могу не согласиться.
