### ISSUE TITLE
Автоматизация оптимизации изображений в статьях

### ISSUE THREAD

**Issue by vitalybaev** [web-standards-ru/web-standards.ru#25]
Например, статья: **Чему меня научил год изучения и преподавания доступности**
https://web-standards.ru/articles/what-accessibility-taught-me/
Загружает 3.04 мегабайта ресурсов. Основная проблема - изображения в PNG, самое тяжелое из которых весит 771 кб.
Нужно смотреть в сторону jpg, а лучше конвертировать еще и в webp

**Предложенное решение**
* Храним оригиналы изображений в максимальном качестве
* При сборке генерируем разные размеры изображений + разные форматы (jpg, webp) + оптимизация
* В статьях помещается тег picture со всеми вариантами srcset

**Comment by pepelsbey** [comment]
Я бы посмотрел в сторону автоматизации. Картинки хочется хранить в исходном или близком к тому качестве. А потом уже прогонять их через оптимизаторы при сборке, вставлять всякие `<picture>` с кучей классных параметров.

**Comment by vitalybaev** [comment]
Ну да, этот вариант идеальный, обновлю постановку задачи

**Comment by pepelsbey** [comment]
@MeFoDy ты любитель всяких гуслей, возьмёшь полайвкодить?

**Comment by MeFoDy** [comment]
Берусь сделать на выходных. Заодно `<picture>` таки втащу под ретину и прочие радости жизни с чёткими экранами.

**Comment by pepelsbey** [comment]
Если кто-то будет делать, то есть плагин https://github.com/11ty/eleventy-img

**Comment by akellbl4** [comment]
Возьмусь как доделаю тултипчики ;)

**Comment by higimo** [comment]
@akellbl4 @MeFoDy @immitsu у нас есть #146 вдруг кто-то из вас давно уже хочет заняться чем-то подобным или просто хотите добить PR?

**Comment by akellbl4** [comment]
@higimo я ждал пока мои остальные PR примут, чтобы не плодить энтропию :)

**Comment by immitsu** [comment]
Пересоздал 146 - [PR#205](https://github.com/web-standards-ru/web-standards.ru/pull/205)

**Comment by pepelsbey** [comment]
@monochromer поздно пришёл, но уточню задачу :)

- Форматы: AVIF, WebP, оригинальные, сжатие по умолчанию
- SVG: не оптимизировать
- Игнор: пока допустим, что не нужно
- Удалённые: не нужно
- Обложки: пока нет

**Comment by monochromer** [comment]
@pepelsbey AVIF даёт, конечно, меньший размер, но сборка становится значительно медленнее (у меня занимает около 7 минут):
```
[11ty] Copied 695 files / Wrote 536 files in 440.68 seconds (822.2ms each, v2.0.1)
[11ty] Watching…
[11ty] Server at http://localhost:8080/
[11ty] File changed: eleventy.config.js
[11ty] Wrote 536 files in 6.78 seconds (12.6ms each, v2.0.1)
```

**Comment by pepelsbey** [comment]
@monochromer если это будет только в продакшен-сборке происходить, а при локальном дев-сервере нет — то норм. Ну и можно потом приделать кэши для GitHub Actions.

**Comment by monochromer** [comment]
ок, добавляю тогда, чтобы преобразование изображений было только для прода

**Comment by pepelsbey** [comment]
Спасибо всем, кто принёс задачу, обсуждал и конечно @monochromer, который её дожал :)

Теперь, например, статья «[OKLCH в CSS: по­че­му мы ушли от RGB и HSL](https://web-standards.ru/articles/oklch-in-css-why-quit-rgb-hsl/)» после прочтения съедает всего 700 КБ, а не 2 МБ.
