### ISSUE TITLE
Убрать горизонтальный скрол в мобильной версии

### ISSUE THREAD

**Issue by DKukushkin91** [web-standards-ru/web-standards.ru#257]
При переходе на [статью](web-standarts.ru/articles/css-nesting) есть отрицательные margin у класса .article__heading-wrapper на мобильных устройствах, из-за этого есть горизонтальный скрол.

**Comment by pepelsbey** [comment]
Спасибо! Будем рады пулреквесту, пока ищем возможность поправить.

**Comment by monochromer** [comment]
Возможно, стоит удалить правый padding (`padding-right: 16px`), чтобы картинка была точно по краю блока:

![image](https://user-images.githubusercontent.com/6412192/122653058-919ac300-d15b-11eb-8a5b-acf615aea9a7.png)
