### ISSUE TITLE
Контент статьи уходит за границы экрана в статье "Элементы i, b, em и strong"

### ISSUE THREAD

**Issue by vitalybaev** [web-standards-ru/web-standards.ru#26]
https://web-standards.ru/articles/i-b-em-strong-elements/
Из-за вложенных `blockquote` (судя по всему), ширина контейнера статьи увеличивается, из-за чего часть контента уходит за пределы окна браузера

<img width="1438" alt="Снимок экрана 2020-04-29 в 12 13 57" src="https://user-images.githubusercontent.com/724423/80579545-e983e100-8a12-11ea-9323-5e20b4ffc262.png">

**Comment by pepelsbey** [comment]
Спасибо, поправил!
