### ISSUE TITLE
Прозрачный фон плеера подкаста

### ISSUE THREAD

**Issue by andrikotliar** [web-standards-ru/web-standards.ru#263]
При пролистывании страницы подкаста под плеером видно весь текст, предлагаю добавить белый фон между плеером и верхним краем окна.

![Screenshot_9](https://user-images.githubusercontent.com/44230595/123391938-3460a080-d5a5-11eb-91af-96b08406862c.jpg)

**Comment by pepelsbey** [comment]
Мне кажется, что это нормально. У вас когда попап поверх страницы открывается, то он тоже может немного резать контент и создавать такие штуки. Можно это наоборот подчеркнуть тенью от плеера.

**Comment by andrikotliar** [comment]
@pepelsbey да, вполне согласен с этим утверждением.
