### ISSUE TITLE
caninclude.glitch.me - лежит

### ISSUE THREAD

**Issue by nglazov** [web-standards-ru/web-standards.ru#273]
Сервис из [статьи](https://github.com/web-standards-ru/web-standards.ru/blob/main/src/articles/can-i-include/index.md) - недоступен
![image](https://user-images.githubusercontent.com/10438659/127971292-00d81536-098f-4c78-bb52-d1e59e535a25.png)

**Comment by alexeyten** [comment]
Логичнее жаловаться автору сайта https://github.com/CyberLight/caninclude/issues/64
