### ISSUE TITLE
Добавить timecode на страницу подкаста

### ISSUE THREAD

**Issue by PetePearl** [web-standards-ru/web-standards.ru#296]
Было бы удобно иметь возможность скинуть ссылку на определенный timecode
Например для страницы [Выпуска 316](https://web-standards.ru/podcast/316/) ссылка на тему "события" может выглядеть так:
`https://web-standards.ru/podcast/316?t=110`
Можно get параметр добавлять при нажатии на тему или сделать ссылку "поделиться" при наведении на тему или под блоком темы

**Comment by pepelsbey** [comment]
Привет! Спасибо за идею — она отличная.

Мне кажется, что лучше было бы `/316#01:22`, поскольку гет-параметр запрашивает отдельную копию страницы, то есть рассчитан на обработку на бэкенде, а у нас всё же статика. Так что лучше якорь с таймкодом.

Если будет интересно заняться реализацией — будем рады помочь и ответить на вопросы. Ну или сами поищем ресурсы и время. Ещё раз спасибо!

**Comment by vanyauhalin** [comment]
Привет. [Реализовал](https://github.com/web-standards-ru/web-standards.ru/pull/300) возможность указания якоря с timecode.

Размышлял над тем, чтобы при нажатии на timecode в блоке «Темы», копировался url страницы с якорем, но такое поведение мне показалось не очевидным. Также, в коде есть функция [`parseTimecode`](https://github.com/vanyauhalin/web-standards.ru/blob/d539bf97029b9b13af12926dc61ec3f85ecd77f9/src/scripts/modules/podcast.js#L10), которая полностью дублирует фильтр для 11ty. По хорошему, нужно вынести это в отедльный файл в `helpers` или `scripts/utils`, но подумал, что это лучше сделать в отдельном pr.

**Comment by pepelsbey** [comment]
Готово!
