### ISSUE TITLE
В статье поменять местами колонки с текстом и увеличить ширину текста

### ISSUE THREAD

**Issue by teinett** [web-standards-ru/web-standards.ru#30]
**Где**: страница одной статьи, например, https://web-standards.ru/articles/puppeteer-crawl-to-markdown/.

**Окружение**: смотрю на macOS в Chrome 81. Ширина экрана - 1440 рх.

**Что не так**:
1) в левой колонке очень много свободного места, хотя там размещен только байлайн (автор);
2) при этом в правой колонке помещается текст шириной только в 50-55 символов.

<img width="1398" alt="article" src="https://user-images.githubusercontent.com/1038168/80598430-01b72880-8a32-11ea-920c-c2ac5be219c4.png">

**Что хочется сделать**:
1) поменять местами колонки с текстом и байлайном. Пользователям более привычно читать текст с левой стороны, а дополнительную информацию справа.
2) сделать ширину колонки с текстом больше: от 60 до 80 символов.

**Comment by vitalybaev** [comment]
В целом, я тоже склоняюсь к такому варианту, за сутки я так и не смог окончательно привыкнуть к тексту справа, горасто проще его читать, когда он по центру или даже слева.
Но, здесь всецело вопрос дискуссионный

**Comment by pepelsbey** [comment]
Колонки мы местами менять не будем, но ширину колонки слева нужно уменьшить значительно. Это пока временное решение, так что я бы не вкладывал слишком много усилий в него. Новый дизайн страницы статьи пока в процессе.
