### ISSUE TITLE
из подкаста нельзя перейти на главную страницу.

### ISSUE THREAD

**Issue by korenevskiy** [web-standards-ru/web-standards.ru#303]
Жесть, логотип не является ссылкой на главную страницу сайта. 
Как вообще перейти на главную страницу сайта?

**Comment by pepelsbey** [comment]
Привет, спасибо за репорт. Можно перейти, является ссылкой.

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/105274/194858411-9497e47c-0eac-46be-a0c9-1e2b0c685946.png">

Кстати, попробуйте в следующий раз не хамить: «жесть» — плохое начало баг-репорта.

**Comment by korenevskiy** [comment]
Круто. Спасибо что подправили.
Извените за моё хамство.

**Comment by korenevskiy** [comment]
> Так мы ничего не правили, всё так и было 🤔

Странно. Я мышкой так и сяк водил по логотипу, только текст выделялся, но как ссылка не кликалась.
Тогда в **двойне** извиняюсь. 
Для себя, в будущем перед подобным буду код смотреть, перед тем чтобы кричать.

**Comment by korenevskiy** [comment]
@pepelsbey  Здравствуйте Вадим.
Подскажите. А поиск на  сайте ожидается?
Просто сайт содержим уникальную информацию. Но если нет поиска то сайт нельзя рассматривать как справочник, и как учебное пособие.
Спасибо большое за сайт.

**Comment by pepelsbey** [comment]
@korenevskiy у нас сейчас, к сожалению, нет ресурсов разниматься активной разработкой сайта. Но думаю это может стать хорошей заменой:

https://www.google.com/search?q=Lighthouse+site%3Aweb-standards.ru

**Comment by korenevskiy** [comment]
> @korenevskiy у нас сейчас, к сожалению, нет ресурсов разниматься активной разработкой сайта. Но думаю это может стать хорошей заменой:
> 
> https://www.google.com/search?q=Lighthouse+site%3Aweb-standards.ru

Да, конечно. Я Вас понимаю и полностью согласен, что на все хотелки времени ни когда не хватит.
Но я прошу Вас хотя бы на сайте разместить кнопочку с поиском на Google.
Ведь даже при наличии такой кнопочки можно пользоватся поиском и использовать сайт как справочное пособие.

```HTML
<form  action="https://www.google.com/search">
	<input name="q" type="text">
	<input type="sumbin" value="Поиск по сайту с Google">
</form>
```
или может результат из Google подгружать в контент Ajax`ом.

Но, мне кажется что если так не сделать, то сайт не выживет, так как он мало полезен и не будет аудитории.
А если сделать, это уже то с чем может работать аудитория и возможно аудитории будет много.
PS Я понимаю что Вы знаете как эта форма выше пишется и по лучше меня, я написал код, чтобы Вы больше на этим предложением подумали.
