### ISSUE TITLE
устаревшая ссылка на анкету

### ISSUE THREAD

**Issue by kamunicorn** [web-standards-ru/web-standards.ru#317]
https://github.com/web-standards-ru/web-standards.ru/blob/d7b9874feef363f76990ab3faf6b6bd66388d007/src/articles/path-of-tutor/index.md?plain=1#L142

устаревшая ссылка на анкету - http://goo.gl/forms/pMC7UVjI4mfWdBU33

**Comment by pepelsbey** [comment]
Так бывает, ссылки бьются, особенно когда сайту много лет.
