### ISSUE TITLE
устаревшая ссылка на отзывы об академии

### ISSUE THREAD

**Issue by kamunicorn** [web-standards-ru/web-standards.ru#318]
https://github.com/web-standards-ru/web-standards.ru/blob/d7b9874feef363f76990ab3faf6b6bd66388d007/src/articles/path-of-tutor/index.md?plain=1#L122

https://htmlacademy.ru/blog/91-online-intensive-html-css

**Comment by pepelsbey** [comment]
Мы будем рады пул-реквесту, который это исправит. Спасибо!
