### ISSUE TITLE
Добавить кнопку перемотки назад

### ISSUE THREAD

**Issue by Kreash** [web-standards-ru/web-standards.ru#324]
Очень часто при прослушивании подкаста появляется необходимость отмотать назад на несколько секунд.
И такой функционал довольно распространен среди всевозможных плееров (от spotify до castbox или player FM)
Предлагаю добавить где-нибудь рядом с плеером кнопку перемотки назад на 10 секунд

![image](https://github.com/web-standards-ru/web-standards.ru/assets/54755560/cf7422dc-6b9f-41e2-9bbb-f6032b62af35)

**Comment by inoyakaigor** [comment]
Тоже столкнулся с этой проблемой. Надеюсь на скорый мерж

**Comment by inoyakaigor** [comment]
@pepelsbey что нужно, чтобы PR #325 был смержен?

**Comment by pepelsbey** [comment]
@inoyakaigor нужно найти время чтобы сделать ревью и протестировать фичу. К сожалению, пока его нет.

@MeFoDy @melikhov-dev @meritt может у вас есть?

**Comment by monochromer** [comment]
Оставил пару комментов в PR.
