### ISSUE TITLE
Сделать информер для подкаста

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#338]
Сейчас на сайте такая большая шапка на десктопе потому, что планировалось иметь там два информера для анонсов подкаста и статей:

![image](https://github.com/web-standards-ru/web-standards.ru/assets/105274/04705b33-8fbc-4f90-80ac-cec1b2e7b5c2)

Было бы круто внедрить информер для подкаста, чтобы на первом экране было видно свежий эпизод. [Вот даже дизайн есть](https://www.figma.com/file/t9yNCpSL3mdeUBkaLn9mnl?node-id=4:2&locale=en&type=design).

**Comment by monochromer** [comment]
ок, возьму
