### ISSUE TITLE
Обновить конфиг Stylelint

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#344]
Stylelint дропнул часть правил форматирования в пользу Prettier и посыпались ворнинги:

```
> stylelint
> stylelint "src/styles/**/*.css"

Deprecation warnings:
 - The "at-rule-name-case" rule is deprecated.
 - The "at-rule-semicolon-space-before" rule is deprecated.
 - The "at-rule-name-space-after" rule is deprecated.
```

Тут либо нужно дропнуть эти правила, либо добавить плагин, который их учитывает. Вопрос открытый, можно обсудить тут же :)

**Comment by alkorlos** [comment]
Как лучше поступить в этой ситуации очень хороший вопрос.

Отказываться от правил форматирования не хотелось бы, они дают множество преимуществ. Есть официальное объяснение почему в stylelint 15 правила форматирования стали deprecated [Deprecated stylistic rules](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-15.md#deprecated-stylistic-rules). Помимо прочего там есть фраза:

> When we created these rules, pretty printers (like [Prettier](https://prettier.io/)) didn't exist. They now offer a better way to consistently format code, especially whitespace. Linters and pretty printers are complementary tools that work together to help you write consistent and error-free code.

Идея что форматеры и линтеры разные инструменты отличная, к сожалению инструмента с такими же настройками форматирования как в stylelint 15 не существует, почему команда stylelint решила что prettier альтернатива этим правилам мне не понятно.

По ссылке выше так же есть совет про два плагина:

> Alternatively, you can continue to enforce stylistic consistency with Stylelint by using one of the community plugins that have migrated the deprecated rules:
[stylelint-stylistic](https://www.npmjs.com/package/stylelint-stylistic)
[stylelint-codeguide](https://www.npmjs.com/package/stylelint-codeguide)

Судя по issue, на данный момент, они не полная замена stylelint 15. Но если у кого то есть достаточный опыт их использования который говорит об обратном это было бы интересно.

Выбор сейчас — удалить правила форматирования или использовать неотшлифованный плагин мне не нравится. Этот вопрос относится не только к этому репозиторию, он глобальный, Для своих проектов я решил что торопиться некуда, в настоящее время никаких проблем эта ситуация не доставляет, как минимум дождусь выхода stylelint 16, когда эти плагины пройдут массовое тестирование. Или, возможно, появится форматер разных типов файлов с такими настройками? В любом случае хотелось бы чтобы возможность настроить эти аспекты форматирования не была безвозвратно утеряна.

**Comment by monochromer** [comment]
ESLint кстати тоже отказывается от правил форматирования - https://eslint.org/blog/2023/10/deprecating-formatting-rules/

**Comment by alkorlos** [comment]
По тем же причинам что stylelint.

В качестве альтернативы, так же как в stylelint, предлагают плагин который продолжит поддержку свойств форматирования [@stylistic/eslint-plugin-js](https://eslint.style/packages/js) и, что выглядит перспективнее, специализированный инструмент форматирования [dprint](https://dprint.dev/plugins/typescript/config/). Не знал про него, позволяет настраивать большое количество правил, но я не проверял полный ли паритет с eslint по возможностям. CSS он не поддерживает.

У stylelint в течении нескольких месяцев, видимо, выйдет версия без правил форматирования, у eslint это намного больше времени займет, в следующей минорной версии они станут deprecated, и только через одну мажорную, а может и позже как они сами пишут, их удалят.

**Comment by alkorlos** [comment]
8 декабря вышел stylelint 16, в нем удалены все правила форматирования.
Хорошей альтернативы пока не предложено. Сторонний плагин, похоже, самый приемлемый вариант. Когда проект нужно будет обновлять до stylelint 16 напишите сюда, постараюсь в течении недели подключить сторонний плагин и протестировать что ничего не сломалось. Если будут проблемы отпишу сюда же.

**Comment by pepelsbey** [comment]
@alkorlos если есть интерес повозиться и обновить всё до 16-й версии, велком :) Будем рады пулреквесту.

**Comment by alkorlos** [comment]
Если кто-то найдет отдельный форматер который и стили и скрипты поддерживает, с паритетом возможностей с stylelint и eslint, отписывайтесь, можно будет сделать лучше.
