### ISSUE TITLE
Разбить страницы архива подкастов и статей на страницы

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#345]
Сейчас у нас

- [128 статей](https://web-standards.ru/articles/)
- [390 эпизодов](https://web-standards.ru/podcast/)

Кажется это чересчур для типичного посетителя.

Сколько элементов на странице нужно проверить опытным путём на разных вьюпортах. Можно начать с 10 штук.

Дизайна нет, но можно использовать что-то вроде того, что [есть у тегов](https://web-standards.ru/articles/tags/).

**Comment by monochromer** [comment]
Взял себе
