### ISSUE TITLE
Ссылка на репозиторий

### ISSUE THREAD

**Issue by Kgnx7** [web-standards-ru/web-standards.ru#353]
Не нашел ссылку на репозиторий проекта на сайте [web-standards.ru](https://web-standards.ru).
Мне кажется было бы полезно добавить.

_Если ссылка все же есть, то где-то в неочевидном месте (ну либо я невнимательный)._

**Comment by pepelsbey** [comment]
Раньше ссылка была в группе иконок соцсетей, но потом её выпилили — она не вписывалась ни в одну группу. Подумаю, как её вернуть!

Ещё в каждой статье есть «Редактировать статью на Гитхабе», но она не такая очевидная. Спасибо за идею :)

**Comment by inoyakaigor** [comment]
@pepelsbey в каком-то смысле Гитхаб это социальная сеть

**Comment by pepelsbey** [comment]
[Добавил](https://github.com/web-standards-ru/web-standards.ru/commit/555c3bd7431b91c6830ee4e95a0b0ecfbfa77a2c) ссылку на Гитхабе в подвале. Спасибо за идею!
