### ISSUE TITLE
Лента не читается RSS агрегатором

### ISSUE THREAD

**Issue by Mendeo** [web-standards-ru/web-standards.ru#361]
Лента https://web-standards.ru/articles/feed содержит ошибки и не читается RSS агрегатором (FreshRSS). Это также можно увидеть, если открыть ссылку в Firefox:
Ошибка синтаксического анализа XML: некорректно
Адрес: https://web-standards.ru/articles/feed/
Строка 13, символ 33:...

Или в Chrome:
This page contains the following errors:
error on line 13 at column 31:...

**Comment by pepelsbey** [comment]
Спасибо за подробности! В чём сложность: XML не должен содержать `--` внутри блока `<![CDATA[…]]>`, а у нас в статьях часто встречаются кастомные CSS-свойства. Но если убрать `CDATA`, как я попытался сделать [в этом пулреквесте](https://github.com/web-standards-ru/web-standards.ru/pull/362), то одиночные `<img>` уже не XML и возникает другая проблема.

В общем, интересная задача. Будем думать. Спасибо!

**Comment by alexeyten** [comment]
А может заменять в тексте вхождения `--` на `-]]><!CDATA[-` ?

**Comment by pepelsbey** [comment]
> А может заменять в тексте вхождения `--` на `-]]><![CDATA[-` ?

Мне больше нравится заменять `<img>` на `<img/>`, честно говоря)

**Comment by monochromer** [comment]
А json-формат фида не подойдёт? Или есть вероятность, что сломаются подписки, так как будет другой файл?

**Comment by pepelsbey** [comment]
Не уверен, насколько хорошая поддержка у JSON-фидов. XML-фид для совместимости всё равно нужен.

**Comment by alexeyten** [comment]
> Мне больше нравится заменять `<img>` на `<img/>`, честно говоря)

А потом найдётся какой-нибудь `<br>`, `<hr>` и прочие `<source>` :smirk:

**Comment by pepelsbey** [comment]
> > Мне больше нравится заменять `<img>` на `<img/>`, честно говоря)
> 
> А потом найдётся какой-нибудь `<br>`, `<hr>` и прочие `<source>` 😏

Ну да, XML-изация нужна полная 🥲

**Comment by pepelsbey** [comment]
Должно стать лучше после https://github.com/web-standards-ru/web-standards.ru/pull/363

https://web-standards.ru/articles/feed/
