### ISSUE TITLE
target="_blank"

### ISSUE THREAD

**Issue by Kgnx7** [web-standards-ru/web-standards.ru#366]
Кажется, что логично открывать ссылки на странице подкаста в новой вкладке по дефолту, чтобы избежать досадное прерывание подкаста.

Подскажите, пожалуйста, почему сейчас выбран `_self`?

**Comment by pepelsbey** [comment]
Спасибо за вопрос, это действительно так.

Мы не выбирали `_self`, мы используем поведение браузера по умолчанию. Если вы хотите открыть ссылку в новой вкладке, то знаете что нажать на клавиатуре или что выбрать из контекстного меню. Наша публика скорее продвинутая в этом смысле.

Мы не пока не занимались плеером на сайте достаточно серьёзно, чтобы его можно было рекомедовать для прослушивания. Это скорее превью эпизода. Хотя бы потому, что навигация между страницами на самом сайте прерывает плеер. Так что `_blank` ничего принципиально не поменяет и мы продолжим рекомендовать нашим слушателям платформы, где нас удобнее слушать — см. список сервисов в подвале, либо любое приложение для подкастов.
