### ISSUE TITLE
Избавиться от Gulp и внедрить всё в сборку Eleventy

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#368]
Ну а зачем иметь лишнюю зависимость :)

Ничего грандиозного [в gulpfile.js](https://github.com/web-standards-ru/web-standards.ru/blob/main/gulpfile.js) не происходит, это всё сравнительно легко переезжает в сборку Eleventy. Вот, например, как обрабатываются ресурсы у меня в блоге: [HTML, CSS, JS, XML](https://github.com/pepelsbey/pepelsbey.dev/blob/main/eleventy.config.js#L51-L167).

**Comment by monochromer** [comment]
В 3-ем Eleventy bundle plugin входит в поставку - можно использовать его.

**Comment by pepelsbey** [comment]
Хмм, не видел его в действии, кроме проектов на WebC.

**Comment by monochromer** [comment]
Взял себе, но если кто-то тоже хочет, то пожалуйста )
