### ISSUE TITLE
Предложение ограничить число элементов в RSS-лентах

### ISSUE THREAD

**Issue by monochromer** [web-standards-ru/web-standards.ru#376]
Сейчас в RSS-ленты попадают абсолютно все элементы коллекций - все статьи и все выпуски подкаста. Предлагаю ограничить число, например 15-20. Будет быстрее сборка и проще некоторым RSS-ридерам переваривать файлы. Возможно, есть доводы, почему должны быть все элементы?

**Comment by pepelsbey** [comment]
Хм, я не замечал сложностей у RSS-ридеров. Фиды статей не растут по понятным причинам. Фид подкаста я бы разве что подумал как сократить, уменьшив количество разметки внутри. Но когда я начинаю об этом думать, всегда упираюсь в мысли:

1. Зачем?
2. Как померить успех?

Вообще есть идея, что экспорт всего контента — это хорошо. Значит можно пройти на любой платформе на 1-й эпизод или 1-ю статью и умилиться, как всё было забавно в 2016 или 2010 году, соответсвенно.

Если речь исключительно про перформанс сборки, то я бы условный DX ставил ниже UX по значимости :) Чтобы у пользователей был весь контент. А какие симптомы ты видишь?

**Comment by monochromer** [comment]
Пока у меня только одна причина - перформанс сборки. Кроме простой вставки в шаблон данных есть ещё минификация.
