### ISSUE TITLE
Слишком низкий контраст visited ссылок

### ISSUE THREAD

**Issue by vitalybaev** [web-standards-ru/web-standards.ru#39]
<img width="644" alt="Снимок экрана 2020-04-30 в 14 08 47" src="https://user-images.githubusercontent.com/724423/80726243-d5240f00-8b0c-11ea-97c0-008c444f4f08.png">

**Comment by Holiden** [comment]
Если брать контраст 4.5:1, то вместо `#b1b3b6` можно использовать наш  `#696969`. Либо `#828282` с контрастом 3.8:1. @pepelsbey, что скажешь?

**Comment by pepelsbey** [comment]
А можно такой же красивый скриншот с вариантами? :)

**Comment by Holiden** [comment]
> А можно такой же красивый скриншот с вариантами? :)

Конечно!)

![image](https://user-images.githubusercontent.com/48956742/80789653-ceea6d00-8bb6-11ea-81d5-2d2eb59868da.png)

Autoprefixer - цвет сейчас #b1b3b6, контраст 2.1:1.
postcss-preset-env - цвет #696969, контраст 4.5:1, что соответствует [минимальному контрасту](https://www.w3.org/TR/WCAG21/#contrast-minimum).
babel-preset-env - цвет #828282, контраст 3.8:1.

**Comment by pepelsbey** [comment]
Цвет мелкий, я бы лучше тогда `#696969` взял для 4.5
