### ISSUE TITLE
Добавить ESLint

### ISSUE THREAD

**Issue by vitalybaev** [web-standards-ru/web-standards.ru#40]

**Comment by alkorlos** [comment]
Какие правила возьмем за основу? Судя по текущему коду можно standardjs взять, добавив обязательные точки с запятой, потом при необходимости еще какие то правила менять.

**Comment by pepelsbey** [comment]
А может нам просто начать собирать свой? Взять и добавить вещи, которые кажутся правильными и постепенно наращивать вместе с кодовой базой.

**Comment by vitalybaev** [comment]
> А может нам просто начать собирать свой? Взять и добавить вещи, которые кажутся правильными и постепенно наращивать вместе с кодовой базой.

Отличная идея. Не будет ничего лишнего, начнем с малого.

**Comment by alkorlos** [comment]
Это идеальный способ добавления eslint, если есть человек который очень хорошо знает js и eslint, конечно написать под себя всегда лучше всего, но у eslint под триста правил, у многих есть опции, у эти правила порой влияют/зависят друг от друга.
Написать конфиг eslint самим так чтобы правил было достаточно для комфортной работы и для того чтобы нельзя было написать кривой код будет не просто. Обычно или берут что-то готовое и страдая подстраиваются (как с prettier) или взяв готовое решение, тестируют и меняют под себя, это намного быстрее и проще.
Я недавно [разбирал](https://github.com/alkorlos/bundler/blob/master/.eslintrc.js) правила standardjs переводя их для лучшего понимая, и просто это заняло немало времени. Eslint значительно сложнее чем stylelint.
Но если кто-то чувствует в себе силы взяться за такое будет классно.

**Comment by ivanov-v** [comment]
> Это идеальный способ добавления eslint, если есть человек который очень хорошо знает js и eslint, конечно написать под себя всегда лучше всего, но у eslint под триста правил, у многих есть опции, у эти правила порой влияют/зависят друг от друга.
> Написать конфиг eslint самим так чтобы правил было достаточно для комфортной работы и для того чтобы нельзя было написать кривой код будет не просто. Обычно или берут что-то готовое и страдая подстраиваются (как с prettier) или взяв готовое решение, тестируют и меняют под себя, это намного быстрее и проще.
> Я недавно [разбирал](https://github.com/alkorlos/bundler/blob/master/.eslintrc.js) правила standardjs переводя их для лучшего понимая, и просто это заняло немало времени. Eslint значительно сложнее чем stylelint.
> Но если кто-то чувствует в себе силы взяться за такое будет классно.

Есть какие-нибудь примеры страданий с **prettier**? Я юзаю его в связке с **eslint** и никогда не страдал.

**Comment by pepelsbey** [comment]
> Есть какие-нибудь примеры страданий с prettier?

Неудобный, избыточный стиль кода, который за тебя решили какие-то JS-чудаки — вот такой пример страдания.

**Comment by ivanov-v** [comment]
> > Есть какие-нибудь примеры страданий с prettier?
> 
> Неудобный, избыточный стиль кода, который за тебя решили какие-то JS-чудаки — вот такой пример страдания.

Местами выдаёт не то, что ожидал, но в целом всегда красиво получается. Видимо не для всех инструмент)

**Comment by alkorlos** [comment]
Да, тут каждому свое, в теории идея универсальных правил которыми будут пользоваться все разработчики в мире и легко понимать код друг друга хороша, но на практике у всех разные мнения на базовые вещи вроде табы или пробелы, нужны точки с запятой в js или нет и т.д. Не говоря о оформлении кода в целом.
Так что пока, чаще всего, удобнее в рамках отдельных команд договариваться.
