### ISSUE TITLE
Фильтр 11ty для ленивой загрузки видео

### ISSUE THREAD

**Issue by PsarewIvan** [web-standards-ru/web-standards.ru#41]
В #7 мы сделали облегченную версию для youtube-плеера. Минус той реализации - для каждого видео необходимо писать один и тот же код в статьях.
Задача состоит в том, чтобы сделать фильтр, который из одного тега (предположительно `<video>`) создавал нужную html-структуру для ленивой загрузки.

**Comment by PsarewIvan** [comment]
Беру в работу.
Если есть у кого идеи, как сделать лучше - буду рад услышать :)

**Comment by pepelsbey** [comment]
Если мы говорим про фильтр для видео с Ютуба, то тут скорее нужно искать `<iframe>` с подходящим `src` и уже его заменять на плеер. Можно потом развить идею и похожим образом встраивать другие фреймы — например, CodePen. У них тоже можно взять картинку заглушки и т.п. вещи.

**Comment by pepelsbey** [comment]
Точнее, не фильтр, а трансформацию, [см. документацию](https://www.11ty.dev/docs/config/#transforms).
