### ISSUE TITLE
Сломались картинки в статьях

### ISSUE THREAD

**Issue by Holiden** [web-standards-ru/web-standards.ru#45]
Кажется [это](https://github.com/web-standards-ru/web-standards.ru/commit/d09dd1c9b7b609fb120987d062b8a4aa3eaa4af5#diff-fedb490f4508aaac246a6aad85f6dc84L198-L209) в ПР #22 сломало все картинки в статьях.
[линк](https://web-standards.ru/articles/what-accessibility-taught-me/) [линк](https://web-standards.ru/articles/six-things-i-check/)

**Comment by pepelsbey** [comment]
Чиню
