### ISSUE TITLE
Большое количество повторяющихся медиа выражений

### ISSUE THREAD

**Issue by in-in** [web-standards-ru/web-standards.ru#53]
Например, финальный файл `dist/styles/styles.css` содержит 55 вхождений для _min-width:1024px_.

_csso_ умеет мержить MQ и это самый простой вариант решить эту проблему
```diff
// gulpfile.js
- require('postcss-csso'),
+ require('postcss-csso')({forceMediaMerge: true}),
```
![201231588384648](https://user-images.githubusercontent.com/8797432/80852566-4b6e6180-8c32-11ea-8405-61e23b2ba863.png)

Да, опция опасная, но так как проект новый можно не боятся что-то сильно сломать. Я бегло просмотрел вёрстку с оптимизированными MQ и серьёзных косяков не заметил. 

Проблема не критическая и жить можно, но при росте сайта дубли будут расти тоже и в будущем это будет сложнее разруливать.Ну и конечно это просто красиво и логично когда в одно MQ собраны все нужные стили.

**Comment by Holiden** [comment]
Мы наоборот разбирали кучные медиа выражения по классам для удобства чтения кода.

**Comment by pepelsbey** [comment]
А если сравнивать после gzip? :)

**Comment by pepelsbey** [comment]
Сравнил:

```
orig: 38621 bytes
gzip: 6701 bytes (17.35%)

orig: 34082 bytes
gzip: 6453 bytes (18.93%)
```

**Comment by pepelsbey** [comment]
> Мы наоборот разбирали кучные медиа выражения по классам для удобства чтения кода.

Тут речь про сборку, так что в исходнике мы можем делать что хотим. Кажется, что 3–4 Кб кода для критического для рендеринга ресурса — это хороший выигрыш.

Сделаете пулреквест? :)

**Comment by Holiden** [comment]
> Тут речь про сборку, так что в исходнике мы можем делать что хотим. 

Да точно, изначально не так понял :)

**Comment by higimo** [comment]
#58 ПР пока решили, что опасненько внедрять. После внедрения редизайна можно попробовать по новой. Главное без фанатизма склеивать MQ, сокращения gzip всё равно будет.

**Comment by pepelsbey** [comment]
Пока прикрою, не кажется слишком важным
