### ISSUE TITLE
Внедрить выделение всего кода в примеры

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#56]
См. [Using CSS to Control Text Selection](https://codersblock.com/blog/using-css-to-control-text-selection/)

**Comment by vitalybaev** [comment]
Я бы взял, только не разобрался, как (точнее где) добавлять атрибуты к тегу code, который получается из markdown. Смотрел в доке `markdown-it`, опцию `highlight`, но не завелось

**Comment by pepelsbey** [comment]
Лучше бы сделать это на уровне markdown-it, там точно должны быть какие-то хуки. В крайнем случае, можно сделать через трансформацию, [по примеру видео](https://github.com/web-standards-ru/web-standards.ru/pull/49). Но только в самом крайнем :)

**Comment by Holiden** [comment]
> Я бы взял, только не разобрался, как (точнее где) добавлять атрибуты к тегу code, который получается из markdown. Смотрел в доке `markdown-it`, опцию `highlight`, но не завелось

Я тоже пробовал, только через плагин `markdown-it-attrs`, но у меня тоже не завелось. Может кто-то сможет в нём разобраться :)

**Comment by higimo** [comment]
@Holiden @vitalybaev я не знаю куда это совать, но умею работать с md-it, так что вот вам код для внедрения.

`index.js`
```js
const fencePlugin = md => {
	const renderToken = (tokens, idx, options, env, self) => self.renderToken(tokens, idx, options)
	const defaultRender = md.renderer.rules.fence || renderToken

	md.renderer.rules.fence = (tokens, idx, options, env, self) => {
		const token = tokens[idx]

		token.attrJoin('class', 'my-name-is-slim-shady') // Да, он допишет, при надобности

		return defaultRender(tokens, idx, options, env, self)
	}
}


var md = require('markdown-it')().use(fencePlugin)
var result = md.render('\
# markdown-it rulezz!\n\
\n\
```css\n\
me\n\
```\n\
')

console.log(result)
```

```bash
λ node index.js
<h1>markdown-it rulezz!</h1>
<pre><code class="my-name-is-slim-shady language-css">me
</code></pre>
```

**Comment by higimo** [comment]
`.use(fencePlugin)` — тут ключевое, что я не знаю куда вставлять. То есть нужно найти как подключить плагин и, вероятно, импортнуть его из файла.
