### ISSUE TITLE
Добавить приятный шрифт для сниппетов кода

### ISSUE THREAD

**Issue by MeFoDy** [web-standards-ru/web-standards.ru#6]
Текущий шрифт кириллицей выглядит плохенько. А кириллица есть.

![image](https://user-images.githubusercontent.com/1439919/80509352-f86e8300-8981-11ea-8d58-fff6d6c8fea0.png)

**Comment by pepelsbey** [comment]
Текущий шрифт вообще не задан, то есть `pre { font-family: monospace }` в стилях браузера. Значит у тебя в системе беда с кириллицей :)

**Comment by pepelsbey** [comment]
По дизайну — это RF Rostin, он даже [подключен в стилях](https://github.com/web-standards-ru/web-standards.ru/blob/master/src/styles/fonts.css#L168-L197), но нигде не используется.

**Comment by pepelsbey** [comment]
Теперь красиво

![Uploading image.png…]()
