### ISSUE TITLE
Неприятности типографа

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#60]
Вставил два пробела, заменил дефисы на тире

```diff
- 4. Далее производится проверка на пересечение множеств:
+ 4.  Далее производится проверка на пересечение множеств:
-    - если найдены общие ключевые слова — **положительный вердикт,** теги можно вкладывать.
+    — если найдены общие ключевые слова — **положительный вердикт,** теги можно вкладывать.
```

Заменил дефисы на тире, продублировал запятую снаружи

```diff
- - У вкладываемого тега нужно проверить секцию **Categories,** а у родительского тега — **Content model.**
+ — У вкладываемого тега нужно проверить секцию **Categories,**, а у родительского тега — **Content model.**
```

**Comment by pepelsbey** [comment]
@Mavrin, как думаешь, хотя бы списки поправить можно?

**Comment by Mavrin** [comment]
С запятой однозначно баг и думаю исправляется.
Пробелы это наверное remark вставляет, но проверю, возможно, нельзя починить или будет в другом месте переделывать, и потом падать на editorConfigLint.
С дефисами и тире, не должно менять по причине того что это список?
И можно весь файл целиком.

**Comment by pepelsbey** [comment]
> С дефисами и тире, не должно менять

В маркдауне дефисы в начале строки делают эту строку элементом списка. И если строка в исходнике начинается с дефиса, то такой её и нужно оставить :)

Весь файл: [src/articles/can-i-include/index.md](https://github.com/web-standards-ru/web-standards.ru/blob/master/src/articles/can-i-include/index.md)

**Comment by Mavrin** [comment]
Открой на гитхабе https://github.com/web-standards-ru/web-standards.ru/blob/master/src/articles/can-i-include/index.md заметь он не парсит список. Поэтому и типограф считает это, просто пердложением (но это не точно).

**Comment by Holiden** [comment]
С пробелами `listItemIndent: mixed` в [.remarkrc.js](https://github.com/web-standards-ru/web-standards.ru/blob/master/.remarkrc.js) это свойство должно помочь. Нужно попробовать заменить `mixed` на `2`.

**Comment by Mavrin** [comment]
Там нельзя `2`. Но все верно эта настройка, как раз может помочь, но будет другой сайд-эффект с вложенными списками.
https://github.com/remarkjs/remark/tree/master/packages/remark-stringify#optionslistitemindent
>Style of indentation for list items ('tab', 'mixed' or '1', default: 'tab').

**Comment by Holiden** [comment]
> Там нельзя `2`. Но все верно эта настройка, как раз может помочь, но будет другой сайд-эффект с вложенными списками.
> https://github.com/remarkjs/remark/tree/master/packages/remark-stringify#optionslistitemindent
> 
> > Style of indentation for list items ('tab', 'mixed' or '1', default: 'tab').

Точно, имел ввиду `1`. А с вложенными кажется может помочь плагин [lint-list-item-content-indent](https://github.com/remarkjs/remark-lint/tree/master/packages/remark-lint-list-item-content-indent).

**Comment by Mavrin** [comment]
Посмотри внимательно на что ругается это плагин.
это ок, для еditor config не ок
```
1.·[x] Alpha
···1. Bravo
```
это не ок,  для еditor config ок
```
1.·[x] Charlie
····1. Delta
```

**Comment by Mavrin** [comment]
@pepelsbey со списками все работает хорошо. https://github.com/web-standards-ru/web-standards.ru/pull/64/files. На сайте из-за этого не отображаются списки. 
<img width="865" alt="Screen Shot 2020-05-05 at 21 27 08" src="https://user-images.githubusercontent.com/1193817/81101920-7d741200-8f17-11ea-9091-eb18237fa2b2.png">

**Comment by pepelsbey** [comment]
> Посмотри внимательно на что ругается это плагин.
> это ок, для еditor config не ок

Я не очень понимаю (

**Comment by Mavrin** [comment]
пример ошибки https://github.com/web-standards-ru/web-standards.ru/pull/66
можно еще так настроить https://github.com/web-standards-ru/web-standards.ru/pull/67

**Comment by pepelsbey** [comment]
Скажу честно, я запутался. Я вижу три пулреквеста: #65, #66, #67.

Какой из них нужен и зачем два остальны? :)

**Comment by Mavrin** [comment]
#65 я исправил проблему с пунктуацией (про лишнюю запятую). Его можно мержить.
#66 и #67 это для обсуждения.
#66 это пример, что получится, если  вы ставить в настройках remark на стройку для отступов `1`, в этом случае видишь падает editor config linter.
#67 это пример, что получится, если  вы ставить в настройках remark на стройку для отступов `tab`.

**Comment by pepelsbey** [comment]
А может мы не будем делать пулреквесты, которые не надо мёржить? Сейчас проект активный и хочется в этом как-то ориентироваться. Вот я запутался.

**Comment by Mavrin** [comment]
> > Посмотри внимательно на что ругается это плагин.
> > это ок, для еditor config не ок

> Я не очень понимаю (

Мне как-то нужно было объяснить, кажется, пример, это лучший способ. Можно теги добавлять, что бы не путаться.
