### ISSUE TITLE
Обработать 404 ошибки

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#62]
- Поправить битые ссылки или ресурсы
- Сделать что-то там такое для поисковиков в robots.txt

[400.xlsx](https://github.com/web-standards-ru/web-standards.ru/files/4582482/400.xlsx)

**Comment by MeFoDy** [comment]
По-хорошему нужно сделать правильные редиректы, чтобы те ресурсы, в которые часто стучатся, вели туда, где эти ресурсы лежат сейчас. Вижу в табличке фид про такое.

А мы не хотим отдельную страничку 404 сверстать, а то сейчас nginx торчит наружу некрасивый.

**Comment by pepelsbey** [comment]
Хотим страничку! Если кто-то соберёт простую из того, что есть — настрою сервер, чтобы туда вёл.

Также стоит написать редиректы для поисковиков в robots.txt, чтобы ссылки ушли из индексов. И кроме этого редиректы на уровне сервера. Но нужно сделать анализ таблицы.

**Comment by akellbl4** [comment]
Нет ли ощущения, что многие ссылки из перестали переходить? Как правило сломанные деранжируются из поиска.
Так же в таблице не хватает колонки соответствия с новыми страницами.

А страничку 404 в целом собрать то не сложно, если кто раньше не соберется тоже попробуем что нибудь сообразить

**Comment by pepelsbey** [comment]
@akellbl4 при желании, могу дать доступ в Яндекс Вебмастер и Google Search Console, там уже можно будет покопаться и понять, какие страницы ещё в поиске и что можно сделать.

**Comment by akellbl4** [comment]
@pepelsbey посмотрел еще раз уже существующую табличку и понимаю что мне практически невозможно смапить эту табличку с текущими статьями, потому что я просто не знаю чему соответствовали старые статьи. А для многих других ссылок просто нет разделов.
Удалить страницы из индекса Google можно в [этом разделе](https://www.google.com/webmasters/tools/removals), наверно у Яндекса тоже есть что-то похожее.

А для лучшей индексации верных страниц было бы не плохо добавить `sitemap.xml`
