### ISSUE TITLE
Встраивать youtube-плеер облегченно

### ISSUE THREAD

**Issue by MeFoDy** [web-standards-ru/web-standards.ru#7]
https://web-standards.ru/articles/parent-selector/ — здесь лишний мегабайт приносит только встраивание плеера, без проигрывания. Нужно подключать лениво, можно использовать lite-youtube-embed или решение Вадима Макеева.

**Comment by PsarewIvan** [comment]
Готов сделать по решению @pepelsbey из [№12](https://www.youtube.com/watch?v=4JS70KB9GS0&t=210s)

**Comment by pepelsbey** [comment]
Продано!
