### ISSUE TITLE
Подменять ревизии файлов в манифесте

### ISSUE THREAD

**Issue by nikolai-shabalin** [web-standards-ru/web-standards.ru#72]
Сейчас gulp-таска `'cache:replace'` не меняет ревизии для файлов объявленных в манифесте

Не рабочий вариант

_manifest.json_
```json
"icons": [{
    "src": "/images/icons/160.png", <-----
    "sizes": "160x160",
    "type": "image/png"
  }
```

рабочий вариант
```json
{
    "src": "/images/icons/160-01fef327b3.png", <-----
    "sizes": "160x160",
    "type": "image/png"
}
```

Для того, чтобы заработало нужно поменять путь до файла манифеста в gulp-таске `'cache:replace'`

```js
gulp.task('cache:replace', () => {
    return gulp.src([
            'dist/**/*.{html,css}',
            'dist/manifest-*.json', <-----
        ])
});
```

Не понимаю какую задачу решали с помощью `manifest-*.json`. Вроде как несколько манифестов на проект, но если такого не предполагается, то строку можно поменять на `'dist/manifest.json'` и всё заработает как надо.

**Comment by nikolai-shabalin** [comment]
Могу сделать PR. Дело секундное.

**Comment by pepelsbey** [comment]
Строка `manifest-*.json` предполагает, что манифест тоже версионируется. Но это, к сожалению не так. То есть ошибка есть, но суть в том, что забыли версионировать манифест.
