### ISSUE TITLE
Вычитка статей. Дюжина № 1

### ISSUE THREAD

**Issue by higimo** [web-standards-ru/web-standards.ru#74]
В этих статьях могут быть опечатки, биты ссылки и картинки; неподписанные или повторяющиеся картинки. Картинки без альтов. Правьте смело и присылайте pull request. Если не умеете в гит, но хотите помочь — оставляйте комментарий с ссылкой на статью, цитатой исправляемого текста (для `ctrl+f`) и на что нужно исправить. Исправляющий укажет вас в комментарии коммита в формате `#issueNumber @author исправляет ошибку`

Изучите [как заполнять альты и подписывать изображения](/web-standards-ru/web-standards.ru/blob/master/CONTRIBUTING.md#%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%D0%BC%D0%B8).

----
- [ ] [can-i-include](https://web-standards.ru/articles/can-i-include/)
- [ ] [Доступность и закон](https://web-standards.ru/articles/a11y-and-law/)
- [ ] [Инклюзивные компоненты: сворачиваемые секции](https://web-standards.ru/articles/collapsible-sections/)
- [ ] [Инклюзивные компоненты: слайдер](https://web-standards.ru/articles/a-content-slider/)
- [ ] [Инклюзивные компоненты: список дел](https://web-standards.ru/articles/a-todo-list/)
- [ ] [Исследуем большие экраны](https://web-standards.ru/articles/big-screens/)
- [ ] [Как воспитать дизайнера](https://web-standards.ru/articles/coder-vs-designer/)
- [ ] [Как русскоязычные пользователи с особыми потребностями пользуются сайтами](https://web-standards.ru/articles/a11y-poll-2019/)
- [ ] [Критический CSS + прогрессивный CSS = ?](https://web-standards.ru/articles/critical-and-progressive-css/)
- [ ] [Не проверив HTML5-кода, не суйся в воду — с Майком™ Смитом](https://web-standards.ru/articles/check-it-before-you-wreck-it/)
- [ ] [Невыполненные обещания веб-компонентов](https://web-standards.ru/articles/broken-promise-web-comps/)
- [ ] [О доступности интерфейсов из первых уст](https://web-standards.ru/articles/a11y-users-interview/)

**Comment by w1r3d7** [comment]
**Битые ссылки:**

- [Доступность и закон](https://web-standards.ru/articles/a11y-and-law/)
Текст Директивы.
Текст Раздела 508
Чеклист доступности соответствия Разделу 508 Министерства здравоохранения и социальных служб США.
WCAG 2.0 на английском языке.
WCAG 2.0 на русском языке.

- [Инклюзивные компоненты: сворачиваемые секции](https://web-standards.ru/articles/collapsible-sections/)
aria-controls работает только в JAWS - Открывается только без JS.
больше предпочитают перемещаться по документу по заголовкам, чем по областям - Открывается только без JS.

- [Инклюзивные компоненты: слайдер](https://web-standards.ru/articles/a-content-slider/)
демо с этим методом

- [Исследуем большие экраны](https://web-standards.ru/articles/big-screens/)
монолитный памятник
регионы 
мой пример с колонками 

- [Критический CSS + прогрессивный CSS = ?](https://web-standards.ru/articles/critical-and-progressive-css/)
Ускорение Lenta.ru: 3 человека, 2 недели, улучшение глубины просмотра на 27%,

- [Не проверив HTML5-кода, не суйся в воду — с Майком™ Смитом](https://web-standards.ru/articles/check-it-before-you-wreck-it/)
@sideshowbarker ссылка рабочая, но аккаунт заблокирован
 w3.org/Bugs/Public
ARIA в HTML
Web developer rules for use of ARIA attributes on SVG1.1 elements

- [Невыполненные обещания веб-компонентов](https://web-standards.ru/articles/broken-promise-web-comps/)
HTML-импорты 
заявила:
