### ISSUE TITLE
Добавить оригинальные имена авторов

### ISSUE THREAD

**Issue by alexeyten** [web-standards-ru/web-standards.ru#77]
Сара Суайдан (Sara Soueidan)

Для удобства поиска и понимания 😀

**Comment by pepelsbey** [comment]
А где это лучше сделать?

**Comment by alexeyten** [comment]
В смысле «где»?
Можно в скобках после имени (и мельче)

**Comment by pepelsbey** [comment]
Буквально «где?» Есть много ситуаций, в которых мы выводим имя автора.

**Comment by alexeyten** [comment]
Как минимум в статье.
В списке в мобильном виде может быть не очень красиво.

![Screen Shot 2020-05-14 at 14 14 17](https://user-images.githubusercontent.com/44377/81928014-42e03880-95ed-11ea-8f56-99678efa5314.png)

**Comment by pepelsbey** [comment]
Я бы не стал нагружать карточки статей именами.

**Comment by pepelsbey** [comment]
Честно говоря, я плохо понимаю ценность вывода оригинального имени. Транслитерация помогает всем стесняющимся правильно и одинаково называть авторов. С этого имени всегда идёт ссылка на их сайт или Твиттер, где можно точно посмотреть, кто они такие.

@alexeyten ты не мог бы описать ситуацию подробнее?

**Comment by alexeyten** [comment]
Я уже не уверен.
Может мне просто непривычно видеть такое написание знакомых имён.

**Comment by Holiden** [comment]
@pepelsbey давай тогда закроем ПР.

**Comment by higimo** [comment]
@pepelsbey полагаю, что пока лучше закрыть ишу?

**Comment by pepelsbey** [comment]
И правда
