### ISSUE TITLE
Добавить кнопку копирования ссылки к заголовкам

### ISSUE THREAD

**Issue by vasiliy-dudin** [web-standards-ru/web-standards.ru#82]
Отсюда: #68 

## Зачем
Упростить копирование для всех пользователей, избежать проблем с доступностью на скринридерах.
<br>

## Возможное решение
Предлагаю около заголовков поставить кнопку копирования вместо ссылки. 
[Интерактивный прототип](https://34uhec.axshare.com/#id=1x4bsc&p=page_1&c=1)
![image](https://user-images.githubusercontent.com/3635323/81878871-e0a61a00-9591-11ea-8f1e-a66a55dab9ba.png) ![image](https://user-images.githubusercontent.com/3635323/81878906-f3205380-9591-11ea-9a32-6a8858fb1527.png)

### Описание взаимодействия

1. **При наведении и фокусе** на кнопке показывать кастомный тултип с текстом `Копировать ссылку.` 
Расположение. Идеально, если при скролле тултип менят положение автоматически, как у [popper.js](https://popper.js.org/). И если ему хватает места, то по умолчанию всплывает сверху, так курсор не перекроет собой стрелку тултипа. 
Но если такое разрабатывать дорого, то пусть всплывает всегда снизу, так тоже сойдёт.
Задержка: показывать мгновенно или с небольшой задержкой, миллисекунд 200. 
Для скринридеров: добавить `aria-label="Копировать ссылку на заголовок"`.
3. **По клику** на кнопку копировать ссылку.
4. **После нажатия** показывать, что ссылка скопирована:
    - Менять текст тултипа на `Скопировано`. Заодно можно цвет bg изменить, чтобы такая "обратная связь" интерактива была заметнее. 
Другой вариант вариант — показывать [алёрт](https://kutt.it/dPXDKG), но так чуть хуже, сообщение будет не в поле зрения.
    - Сообщать об этом скринридерам через live region.

**Comment by vitalybaev** [comment]
Хотел бы взять, да обнаружил, что в проекте в принципе отсутствует какая-либо сборка JS. Без неё использовать npm пакеты, тот же Popper получится разве что с помощью umd в виде <script src.... />

@pepelsbey может подскажешь, как тут быть?

**Comment by pepelsbey** [comment]
Я бы сделал [что-то вроде этого](https://github.com/fword-dev/f-word.dev/tree/master/src/scripts) и вот [такой сборки](https://github.com/fword-dev/f-word.dev/blob/master/gulpfile.js#L28-L40). Это будет похоже на то, что у нас работает в стилях.

**Comment by vitalybaev** [comment]
Попробую заняться на выходных

**Comment by akellbl4** [comment]
Как я понимаю, иконка скопировать должна заменить иконку с якорем.
Если работа не начиналась, могу взять.

**Comment by pepelsbey** [comment]
@akellbl4 давай!

**Comment by akellbl4** [comment]
@pepelsbey тот пример сборки который ты привел работает если мы не подключаем библиотеки прямо в js в dev-окружении. Потому что в это время у нас просто копируются все файлы.

Если мы хотим бандлить библиотеку к нам в JS нам надо изменять сборку в сторону того что gulp будет запускать eleventy и собирать js в том числе для dev-окружения. [Вот тут](https://github.com/hirusi/smix-eleventy-starter/blob/master/gulpfile.babel.js) пример того как это можно сделать.

**Comment by pepelsbey** [comment]
@akellbl4 я бы всё же оставил как есть:
- 11ty собирает то, что он видит как данные внутри себя и просто копирует остальное
- Gulp собирает всё, что получилось в результате работы 11ty
Так прозрачнее и не нужно запускать одно через другое.

**Comment by pepelsbey** [comment]
@akellbl4 у меня есть [работающий пример](https://github.com/fword-dev/f-word.dev/tree/master/src/scripts) такой сборки:

Файлы импортируются и просто работают в браузере без сборки:

```js
import './modules/focus-visible.js';
import './modules/tabs.js';
```
Индексный файл подключается как модуль:
```html
<script type="module" src="/scripts/index.js"></script>
```

А потом всё собирается в такое с помощью Rollup:

```
<script src="/index-39204dad36.js"></script>
```

**Comment by akellbl4** [comment]
@pepelsbey да, все верно, я его попробовал взять.

Проблема возникает на уровне подключения модуля из npm-пакетов, то есть что-то типа:
`import { createPopper } from '@popperjs/core';`
И так как Gulp не работает в dev-окружении соответственно библиотека в этот момент не бандлится в файл.

Пока что я просто подключил ее прямо в html с CDN, если это окей то можно так оставить или все таки думать как сделать бандлинг в том числе в dv-окружении, а не только во время боевой сборки.

**Comment by pepelsbey** [comment]
Это ES-модули, там нет никакой магии и пути нужно писать руками:
```
import { createPopper } from 'node_modules/@popperjs/core/dist/esm/index.js';
```
Но я тут очень сомневаюсь, что нам нужна библиотека для тултипов для такой простой задачи.

**Comment by akellbl4** [comment]
Я просто посмотрел изначальное описание задачи. Этот модуль по сути решает проблемы того что тултип может быть обрезан или показать его под кнопкой, а не сверху если заголовок находится прямо у верха окна браузера.
Ну и если не для тултипов то для копирования я бы взял проверенный Clipboard.js потому что с копированием есть много трики моментов, а это протестированное проверенное решение и кстати очень крохотное

**Comment by pepelsbey** [comment]
@akellbl4 этот тултип слишком простой 1–2 слова, его проще сделать на CSS, это точно не стоит зависимости и JS.

Копировать содержимое модуля через `addPassthroughCopy` не нужно, он и так доступен из папки node_modules для второго прохода (Gulp, в нашем случае) и зашивается в JS-бандл силами Rollup.

Я сейчас сделаю пулреквест по описанной выше схеме, чтобы не возникало сомнений.

**Comment by akellbl4** [comment]
Gulp не запускается при запуске `npm start`, поэтому при разработке этот файл не будет доступен

**Comment by pepelsbey** [comment]
При разработке этот файл будет доступен напрямую из node_modules, если добавить к серверу доп. локацию, где искать файлы

**Comment by akellbl4** [comment]
@pepelsbey вот оно что. Может я плохо искал и читал документацию, но не нашел возможности добавить любую папку в дополнение к основному `dist`.
Если подскажешь, что это за настройка было бы крутo.

Продолжив гуглить я нашел, только предложение все таки копировать скрипты:
https://github.com/11ty/eleventy/issues/768

**Comment by pepelsbey** [comment]
Учитывая, что нам это пакет пока не нужен — предлагаю отложить решение задачи :)

**Comment by akellbl4** [comment]
Ок, за то выяснили много разных моментов :)

Просто я думал для копирования взять [ClipboardJS](https://clipboardjs.com) как я выше писал хорошее и проверенное решение.

Но в целом можем попробовать обойтись чем-то типа:
```js
const copyToClipboard = value => {
	const element = document.createElement('textarea');
	
	element.value = value;
	element.setAttribute('readonly', '');
	element.style.position = 'absolute';
	element.style.opacity = '0';
	element.style.width = '0'
	element.style.height = '0'
	document.body.appendChild(element);
	element.select();
	document.execCommand('copy');
	document.body.removeChild(element);
};
```

**Comment by pepelsbey** [comment]
@akellbl4 есть простой и кроссбраузерные [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) для такого.

**Comment by akellbl4** [comment]
@pepelsbey спасибо за подсказку! Мне казалось такое только для браузерных расширений есть :)
Не вижу статьи на веб-стандартах, пора писать?

**Comment by pepelsbey** [comment]
Спасибо! Ждём фичу :)
…и статью тоже

**Comment by higimo** [comment]
@pepelsbey а в этом ишу что-то ещё не доделано? =_=

**Comment by pepelsbey** [comment]
Решено в #141
