### ISSUE TITLE
Карточки «Ещё» под статьёй-фичером сломаны

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards.ru#85]
Сравните:

- https://web-standards.ru/articles/witch-developer/

![Screen Shot 2020-05-26 at 00 47 23](https://user-images.githubusercontent.com/105274/82844804-850d5200-9eea-11ea-9a5c-273f1b75eff3.png)

- https://web-standards.ru/articles/a11y-testing-in-it-academy/

![Screen Shot 2020-05-26 at 00 47 33](https://user-images.githubusercontent.com/105274/82844808-88a0d900-9eea-11ea-838d-4137aa02c0e6.png)

Кажется дело в проверке на `featured: true`, которая не должна влиять на вывод «Ещё».

**Comment by pepelsbey** [comment]
Особенно плохо на мобильной версии

![Screen Shot 2020-05-26 at 12 53 02](https://user-images.githubusercontent.com/105274/82886895-def43300-9f4f-11ea-92ee-3bff0d161882.png)

**Comment by maximys781** [comment]
Дополнения к ранее приложенным скриншотам от Вадима:
Устройство: iPhone 8;
Операционная система: iOS 12.4;
Браузер: Safari.

Отловил в главной новости: https://web-standards.ru/articles/witch-developer/

В других новостях такого нет с превью в анонсах.

**Comment by pepelsbey** [comment]
Поправили! Спасибо всем :)
