### ISSUE TITLE
Пожелания по улучшению дизайна

### ISSUE THREAD

**Issue by pravdinalex** [web-standards-ru/web-standards.ru#87]
Я дико извиняюсь, но у меня есть пожелания к дизайну, когда сайт показывается на десктопе в светлой теме, такие как:
- маленькие поля. Например на главной текст анонсов прижимается к рамкам, логотип к верху и т.д. Нужно сделать поля более пропорциональными контенту.
- неподходящий шрифт в статьях, которые вынуждают ставить letter-spacing, странный шрифт в подзаголовках, опять же вынуждающий добавлять letter-spacing. Мне читать некомфортно: текст получается неестественно растянут. Предлагаю посмотреть на другие шрифты.
![image](https://user-images.githubusercontent.com/2210640/82906378-d3b00000-9f6d-11ea-8773-d1c01bc6232f.png)
- borders. Тёмные и дерзкие.  Предлагаю сделать светлее, и не смыкать бордеры в таблицу. На странице статьи они например не смыкаются с тёмным блоком (но там тоже увеличить бы отступы).

На мой взгляд поправленные отступы и бордеры должны выглядеть как-то так:
![image](https://user-images.githubusercontent.com/2210640/82908145-3c987780-9f70-11ea-9fad-83b2e8f304aa.png)

Больше всего меня умилило как на hover реагирует логотип на некоторых страницах статей, например тут https://web-standards.ru/articles/what-accessibility-taught-me/
Не знаю, баг или фича, но именно это вынудило меня поставить ишью. 
![image](https://user-images.githubusercontent.com/2210640/82906270-a7947f00-9f6d-11ea-9b99-8712c14e9e24.png)

**Comment by vitalybaev** [comment]
Со своей стороны могу точно согласиться со шрифтом и его кернингом:
1. Очень горизонтально вытянутый шрифт, степень сложности чтения высокая
2. Кернинг обычного текста - лично я не вижу смысла менять базовые параметры, ну или хотя бы использовать в половину меньше. Для меня чтение текста станет приятнее.
3. Ховер на логотипе у меня тоже вызвал удивление.

Остальное на мой взгляд вкусовщина, а вот указанные пункты с удовольствием бы вынес на обсуждение

**Comment by pepelsbey** [comment]
Спасибо за фидбек! Из всего упомянутого, наиболее серьёзным кажется читабельность текста. Мы ей сейчас занимаемся и будем конечно же учитывать отзывы. Трекинг (letter-spacing) в заголовках обусловлен тем, что это прописные и там разрядка принята для читабельности. Нужно посмотреть, не слишком ли она сильная, по дизайну. Думаю, что ховер из шапки тоже уйдёт, его мало кто понял.

Задачу пока закрою, но по по лейблу её можно будет найти. Ещё раз спасибо большое :)

**Comment by cawa-93** [comment]
Есть мысли касательно текста? Мне очень не комфортно читать на ноутбуке (1920×1080).
